export default {
  languageCode: "en",
  languageName: "English",
  conjunction: "and",
  one: [
    "robes",
    "reception",
    "accumulation",
    "mineral water",
    "stunts",
    "action figures",
    "accession",
    "airplanes",
    "affection",
    "affinity",
    "helpers",
    "wings",
    "breaths",
    "cheerfulness",
    "swings",
    "admiration",
    "love",
    "angle",
    "anguish",
    "anxiety",
    "appearance",
    "kites",
    "architectures",
    "rainbows",
    "harmony",
    "arts",
    "towels",
    "kindergarten",
    "assemblies",
    "attendants",
    "attention",
    "activities",
    "attraction",
    "authenticity",
    "advancement",
    "happenings",
    "awareness",
    "actions",
    "dances",
    "dance",
    "dolls",
    "fog banks",
    "boats",
    "barriers",
    "basilicas",
    "bas-reliefs",
    "beats",
    "bibs",
    "carbonated drinks",
    "bicycles",
    "beer",
    "cookies",
    "bloody mary",
    "bubbles",
    "water bottles",
    "cooler bags",
    "brandy",
    "breezes",
    "blizzards",
    "burbon",
    "compass",
    "busts",
    "coffee",
    "caipirinha",
    "heat",
    "changes",
    "canoes",
    "candy",
    "character",
    "portable chargers",
    "meat",
    "trolleys",
    "castles",
    "cathedrals",
    "usb cables",
    "celebration",
    "champagne",
    "churches",
    "canopies",
    "cyclone",
    "belts",
    "chocolate",
    "bowls",
    "cocktails",
    "consistency",
    "coincidence",
    "collaborators",
    "collaboration",
    "collars",
    "interviews",
    "knives",
    "understanding",
    "understanding",
    "communication",
    "fellowship",
    "concerts",
    "concepts",
    "conclusion",
    "concord",
    "seasonings",
    "sharing",
    "conditions",
    "conferences",
    "confusion",
    "knowledge",
    "consequences",
    "preservation",
    "consistency",
    "airtight containers",
    "continuity",
    "contradiction",
    "controls",
    "conventions",
    "convergence",
    "conversations",
    "cooperation",
    "blankets",
    "comforter covers",
    "jump ropes",
    "horns",
    "currents",
    "lanes",
    "constancy",
    "construction",
    "constructions",
    "creation",
    "creams",
    "growth",
    "ridges",
    "spoons",
    "headphones",
    "curiosities",
    "pillows",
    "case",
    "dance",
    "delicacy",
    "disappointment",
    "dialogues",
    "debates",
    "statement",
    "amateurs",
    "addiction",
    "paintings",
    "directions",
    "discipline",
    "discussions",
    "drawings",
    "despair",
    "fun",
    "sweetness",
    "sorrow",
    "doubts",
    "durability",
    "hardness",
    "buildings",
    "effects",
    "elephants",
    "helicopters",
    "emergency",
    "emotion",
    "empathy",
    "energy",
    "herbs",
    "performances",
    "existence",
    "outcome",
    "expansion",
    "exploration",
    "exposures",
    "expression",
    "expressions",
    "essence",
    "ecstasy",
    "euphoria",
    "events",
    "evolution",
    "facts",
    "happiness",
    "phenomena",
    "firmness",
    "celebration",
    "flowers",
    "forks",
    "cheeses",
    "formation",
    "camp stove",
    "fortress",
    "strength",
    "photographs",
    "landslides",
    "freshness",
    "frisbee",
    "fruit",
    "escape",
    "lightning",
    "tunnels",
    "ice cream",
    "generation",
    "kindness",
    "gestures",
    "gin",
    "toys",
    "educational toys",
    "games",
    "joy",
    "youth",
    "giraffes",
    "glory",
    "drops",
    "droplets",
    "gumdrops",
    "graffiti",
    "hail",
    "grids",
    "guard",
    "owls",
    "guide",
    "hobbies",
    "ideas",
    "identity",
    "illuminations",
    "illustrations",
    "images",
    "impediments",
    "enchantment",
    "embodiment",
    "incentives",
    "uncertainty",
    "incitements",
    "encounters",
    "inquiry",
    "indecision",
    "directions",
    "inferiority",
    "enlargement",
    "enlargement",
    "inhibitions",
    "integrity",
    "interactions",
    "interest",
    "interests",
    "intimacy",
    "entertainment",
    "insights",
    "invention",
    "irradiations",
    "inspirations",
    "kayaks",
    "lakes",
    "lagoons",
    "lamps",
    "flashes",
    "lanterns",
    "sheets",
    "lions",
    "limits",
    "padlocks",
    "lights",
    "toy cars",
    "manifestation",
    "maintenance",
    "seas",
    "masks",
    "mattresses",
    "mats",
    "pencils",
    "wonder",
    "improvement",
    "migrations",
    "patterns",
    "multiplication",
    "scooters",
    "monuments",
    "exhibitions",
    "motivations",
    "mice",
    "movements",
    "rotational movements",
    "museums",
    "mutations",
    "birth",
    "nature",
    "nervousness",
    "snow",
    "snowfall",
    "clouds",
    "nakedness",
    "numbers",
    "oceans",
    "umbrellas",
    "umbrellas",
    "waves",
    "works",
    "opposition",
    "organization",
    "originality",
    "horizon",
    "oscillations",
    "observation",
    "obstacles",
    "pans",
    "landscapes",
    "buildings",
    "balls",
    "swamps",
    "bread",
    "panorama",
    "pants",
    "slippers",
    "wigs",
    "passages",
    "pastimes",
    "passion",
    "pasta",
    "skates",
    "fear",
    "hairs",
    "furs",
    "stuffed animals",
    "markers",
    "pots",
    "perception",
    "performance",
    "personality",
    "fish",
    "pleasure",
    "plants",
    "dishes",
    "fins",
    "rains",
    "water guns",
    "paints",
    "feathers",
    "quilts",
    "cutlery",
    "concern",
    "presence",
    "processes",
    "progress",
    "protection",
    "point of view",
    "puzzle",
    "framework",
    "gatherings",
    "frogs",
    "representations",
    "realization",
    "reactions",
    "plays",
    "regulation",
    "relaxation",
    "insect repellents",
    "resistance",
    "breathing",
    "restrictions",
    "research",
    "recognition",
    "recreation",
    "reflections",
    "refuge",
    "rebirth",
    "rest",
    "reproduction",
    "laughter",
    "reserve",
    "laughter",
    "responses",
    "results",
    "portraits",
    "meetings",
    "sleeping bags",
    "wisdom",
    "sauces",
    "preservation",
    "sanctuaries",
    "soaps",
    "exchanges",
    "boxes",
    "scenes",
    "skepticism",
    "jokes",
    "bondage",
    "scarves",
    "sparks",
    "slides",
    "discovery",
    "scotch",
    "sculptures",
    "buckets",
    "chairs",
    "sign",
    "seminars",
    "sensation",
    "feeling",
    "paths",
    "feeling",
    "stools",
    "skateboards",
    "suffering",
    "solidity",
    "surprise",
    "smiles",
    "surveillance",
    "suspicion",
    "substance",
    "supports",
    "submarines",
    "overlap",
    "brushes",
    "portable speakers",
    "shows",
    "sparkling wine",
    "scales",
    "ponds",
    "statues",
    "stimuli",
    "roads",
    "layers",
    "musical instruments",
    "astonishment",
    "success",
    "juices",
    "suggestions",
    "support",
    "entertainment",
    "development",
    "carpets",
    "keyboards",
    "tables",
    "cups",
    "pans",
    "televisions",
    "leisure",
    "thunderstorms",
    "tents",
    "tentacles",
    "thermos",
    "terror",
    "typhoons",
    "flashlight",
    "tornadoes",
    "towers",
    "cakes",
    "tablecloths",
    "quilts",
    "transformation",
    "tricycles",
    "triumph",
    "sadness",
    "tsunami",
    "thunder",
    "tea",
    "union",
    "vacation",
    "avalanches",
    "variations",
    "winds",
    "vegetable",
    "vibrations",
    "routes",
    "vigilance",
    "constraints",
    "wine",
    "life",
    "victory",
    "flights",
    "workshops",
    "backpacks",
    "paws",
    "fangs",
    "mosquito nets",
  ],
  two: [
    "with a call to nature",
    "with a hidden secret",
    "with a whiff of epic adventure",
    "with an infectious smile",
    "with a sip of adventure",
    "with a touch of drama",
    "with a touch of elegance",
    "with a touch of madness",
    "with a touch of magic",
    "with an adventurous soul",
    "with a poetic soul",
    "with a rebellious soul",
    "with a wild soul",
    "with a caress of serenity",
    "with a note of melancholy",
    "with a note of mystery",
    "with a note of romance",
    "with a hint of sarcasm",
    "with a splash of magic",
    "with a trace of nostalgia",
    "with dark chocolate",
    "of crystal",
    "of fire and ice",
    "with a touch of mystery and suspense",
    "of night",
    "of pure fantasy",
    "in the dark",
    "of broken dreams",
    "in a dream",
    "after a long meditation",
    "during a full moon",
    "during an intergalactic journey",
    "during a yoga class",
    "during a sleepless night",
    "in vintage style",
    "in a secret laboratory",
    "in a Pirandello book",
    "in Naples",
    "in a digital world",
    "in a world where gravity is different",
    "in a world where magic is real",
    "in an enchanted world",
    "in a parallel world",
    "in an unknown world",
    "in a fairy realm",
    "in a parallel universe",
    "in a surreal atmosphere",
    "in an alternate dimension",
    "while listening to classical music",
    "in the mind of a computer scientist",
    "in the mind of an artist",
    "in the mind of a child",
    "in the mind of a manager",
    "in the mind of an eternal being",
    "in the mind of a philosopher",
    "in the mind of a madman",
    "in the mind of a healer",
    "in the mind of a magician",
    "in the mind of a mad mathematician",
    "in the mind of a poet",
    "in the mind of a romantic poet",
    "in the mind of a dreamer",
    "in the mind of a traveler",
    "in the mind of a visionary",
    "in the mind of an ancient deity",
    "in the mind of a witch",
    "in the mind of a mad scientist",
    "in the mind of a sorcerer",
    "under the breath of a unicorn",
    "under the reflection of a pool of water",
    "under the touch of a fairy",
    "under the light of the setting sun",
    "under the light of the full moon",
    "under a shower of shooting stars",
    "between the pages of a science fiction book",
    "at hogwarts",
    "in the library",
    "at the movies",
    "if it were advertised by Apple",
    "in black and white",
    "in 3024.",
  ],
  nerd: [
    "Codemotion",
    "Byte",
    "Pixel",
    "Algorithm",
    "Code",
    "Debugging",
    "Server",
    "Cloud",
    "Hardware",
    "Software",
    "Hacker",
    "Bit",
    "Firewall",
    "Database",
    "C++",
    "Python",
    "JavaScript",
    "AI",
    "Router",
    "Linux",
    "Terminal",
    "Bug",
    "Compiler",
    "Framework",
    "API",
    "GitHub",
    "Encryption",
    "Binary Code",
    "HTML",
    "CSS",
    "IoT (Internet of Things)",
    "Firmware",
    "VR (Virtual Reality)",
    "AR (Augmented Reality)",
    "Blockchain",
    "Cybersecurity",
    "Quantum Computing",
    "SSD",
    "HTTP",
    "FTP",
    "LAN",
    "GUI (Graphical User Interface)",
    "Open Source",
    "Kernel",
    "Emulator",
    "BIOS",
    "Overclocking",
    "Proxy",
    "URL",
    "DNS",
    "Torrent",
    "Browser",
    "VPN",
  ],
};
