export default {
  languageCode: "en",
  languageName: "English",
  conjunction: "and",
  one: [
    "robes",
    "reception",
    "accumulation",
    "mineral water",
    "stunts",
    "action figures",
    "accession",
    "airplanes",
    "affability",
    "fascination",
    "affection",
    "affinity",
    "helpers",
    "wings",
    "breaths",
    "enlargement",
    "cheerfulness",
    "children's swings",
    "swinging",
    "ambivalence",
    "bewitchment",
    "admiration",
    "love",
    "loving",
    "angle",
    "anguish",
    "anxiety",
    "appearance",
    "endorsements",
    "kites",
    "architectures",
    "rainbows",
    "harmony",
    "arts",
    "towels",
    "kindergarten",
    "assemblies",
    "attendants",
    "subjugation",
    "attention",
    "acts",
    "relevance",
    "activity",
    "attraction",
    "actualization",
    "authenticity",
    "advancement",
    "occurrences",
    "awareness",
    "actions",
    "dances",
    "dance",
    "dolls",
    "fog banks",
    "boats",
    "barriers",
    "basilicas",
    "bas-reliefs",
    "camping batteries",
    "beats",
    "beats",
    "bibs",
    "benevolent",
    "carbonated drinks",
    "children's bicycles",
    "beer",
    "cookies",
    "bloody mary",
    "bubbles",
    "water bottles",
    "cooler bags",
    "brandy",
    "breezes",
    "hoarfrosts",
    "blizzards",
    "burbon",
    "compass",
    "busts",
    "coffee",
    "caipirinha",
    "heat",
    "changes",
    "canoes",
    "candy",
    "character",
    "portable chargers",
    "cuteness",
    "meat",
    "trolleys",
    "playhouses",
    "cases",
    "castles",
    "catamarans",
    "cathedrals",
    "usb cables",
    "celebration",
    "champagne",
    "churches",
    "canopies",
    "cyclone",
    "belts",
    "chocolate",
    "bowls",
    "circumstances",
    "tufts",
    "wisps",
    "adjuvants",
    "cocktails",
    "consistency",
    "cognac",
    "cognitions",
    "coincidence",
    "collaborators",
    "collaboration",
    "collars",
    "interviews",
    "knives",
    "behaviors",
    "understanding",
    "understanding",
    "understandings",
    "communication",
    "communications",
    "fellowship",
    "concerts",
    "concepts",
    "conclusion",
    "concord",
    "concretization",
    "seasonings",
    "sharing",
    "conditions",
    "conferences",
    "conformity",
    "confusion",
    "knowledge",
    "consciousness",
    "consequences",
    "preservation",
    "consistency",
    "hermetic containers",
    "continuity",
    "contradiction",
    "controls",
    "conventions",
    "convergence",
    "conversations",
    "cooperation",
    "blankets",
    "comforter covers",
    "jump ropes",
    "friendliness",
    "horns",
    "corporatization",
    "currents",
    "lanes",
    "cosmopolitan",
    "constancy",
    "construction",
    "constructions",
    "creation",
    "creams",
    "growth",
    "ridges",
    "spoons",
    "caps",
    "heaps",
    "curiosities",
    "pillows",
    "decorative pillows",
    "inflatable pillows",
    "pet pillows",
    "storage",
    "daiquiri",
    "dance",
    "delicacy",
    "disappointment",
    "dialogues",
    "debates",
    "statement",
    "dilation",
    "dilution",
    "addiction",
    "paintings",
    "directions",
    "discernments",
    "discipline",
    "discussions",
    "drawings",
    "disillusionment",
    "despair",
    "fun",
    "sweetness",
    "sorrow",
    "doubts",
    "durability",
    "hardness",
    "buildings",
    "effects",
    "elephants",
    "helicopters",
    "emanations",
    "emergency",
    "emotion",
    "empathy",
    "energy",
    "herbs",
    "performances",
    "existence",
    "outcome",
    "expansion",
    "exploration",
    "exposures",
    "expression",
    "expressions",
    "essence",
    "ecstasy",
    "euphoria",
    "events",
    "evolution",
    "evolutions",
    "fascination",
    "facts",
    "happiness",
    "phenomena",
    "firmness",
    "celebration",
    "flames",
    "flowers",
    "flows",
    "fluctuations",
    "electrocution",
    "thunderbolts",
    "forks",
    "cheeses",
    "formation",
    "camp stove",
    "fortress",
    "fortresses",
    "strength",
    "photographs",
    "landslides",
    "freshness",
    "frisbee",
    "fruit",
    "escape",
    "lightning",
    "tunnels",
    "frosts",
    "frosts",
    "generation",
    "kindness",
    "genuineness",
    "gestures",
    "gin",
    "gin tonic",
    "toys",
    "educational toys",
    "games",
    "joy",
    "youth",
    "giraffes",
    "glory",
    "drops",
    "droplets",
    "gumdrops",
    "graffiti",
    "hail",
    "camping grids",
    "guard",
    "owls",
    "guide",
    "hobbies",
    "ideas",
    "identity",
    "illuminations",
    "illustrations",
    "images",
    "impasses",
    "impediments",
    "enchantment",
    "embodiment",
    "incentives",
    "uncertainty",
    "incitements",
    "encounters",
    "inquiry",
    "indecision",
    "indication",
    "directions",
    "inferiority",
    "inflation",
    "enlargement",
    "enlargement",
    "inhibitions",
    "integrity",
    "interactions",
    "interest",
    "interests",
    "interchanges",
    "intimacy",
    "entertainment",
    "insights",
    "invention",
    "irish coffee",
    "irradiations",
    "inspirations",
    "kayaks",
    "lakes",
    "lagoons",
    "lamps",
    "flashes",
    "lanterns",
    "sheets",
    "lions",
    "limits",
    "padlocks",
    "camping lights",
    "toy cars",
    "manifestation",
    "maintenance",
    "tides",
    "margarita",
    "seas",
    "martinis",
    "masks",
    "diving masks",
    "mattresses",
    "mattresses",
    "materialization",
    "pencils",
    "memorials",
    "wonder",
    "improvement",
    "migrations",
    "patterns",
    "mojitos",
    "multiplication",
    "scooters",
    "monuments",
    "mosques",
    "moscow mule",
    "exhibitions",
    "motivations",
    "mouse",
    "movements",
    "rotary movements",
    "museums",
    "mutations",
    "mutuality",
    "birth",
    "nature",
    "dead naturalness",
    "mists",
    "negroni",
    "nervousness",
    "snow",
    "snowfall",
    "standardization",
    "clouds",
    "nakedness",
    "numbers",
    "obedience",
    "oceans",
    "umbrellas",
    "umbrellas",
    "waves",
    "works",
    "opposition",
    "organization",
    "orientations",
    "originality",
    "horizon",
    "oscillations",
    "observation",
    "obstacles",
    "outcome",
    "paddle board",
    "pans",
    "landscapes",
    "landscape",
    "buildings",
    "balls",
    "beach balls",
    "swamps",
    "bread",
    "panorama",
    "panoramas",
    "pants",
    "slippers",
    "wigs",
    "passages",
    "pastimes",
    "passion",
    "pasta",
    "roller skates",
    "fear",
    "hairs",
    "furs",
    "stuffed animals",
    "markers",
    "pots",
    "perception",
    "perceptions",
    "performance",
    "permanence",
    "perplexity",
    "persistence",
    "personality",
    "fish",
    "pleasure",
    "plants",
    "dishes",
    "pina colada",
    "fins",
    "rains",
    "water guns",
    "paints",
    "feathers",
    "quilts",
    "camping cutlery",
    "concern",
    "presence",
    "preservation",
    "processes",
    "processes",
    "procreation",
    "progress",
    "progress",
    "prosecco",
    "perspective",
    "proximity",
    "protection",
    "pulse",
    "point of reference",
    "point of view",
    "puzzle",
    "framework",
    "gatherings",
    "frogs",
    "representations",
    "reviews",
    "realization",
    "reactions",
    "reciprocity",
    "recitals",
    "recitals",
    "regulation",
    "relaxation",
    "relaxation",
    "insect repellents",
    "repressions",
    "resilience",
    "resilience",
    "breathing",
    "restitutions",
    "restrictions",
    "feedback",
    "search",
    "recognition",
    "recreation",
    "reflections",
    "refuge",
    "regeneration",
    "stiffness",
    "rebirth",
    "renewal",
    "rest",
    "reproduction",
    "laughter",
    "reserve",
    "laughter",
    "responses",
    "results",
    "returns",
    "portraits",
    "meetings",
    "revelation",
    "robustness",
    "rotations",
    "dews",
    "rum",
    "sleeping bags",
    "wisdoms",
    "sake",
    "sauces",
    "safeguard",
    "shrines",
    "shrine",
    "soaps",
    "exchanges",
    "boxes",
    "scenery",
    "scenes",
    "skepticism",
    "jokes",
    "bondage",
    "scarves",
    "sparks",
    "baby slides",
    "bewilderment",
    "discovery",
    "foreshortening",
    "scotch",
    "sculptures",
    "beach buckets and scoops",
    "chairs",
    "camping chairs",
    "signaling",
    "sign",
    "seminars",
    "sensation",
    "sensibility",
    "sensuality",
    "paths",
    "feeling",
    "bondage",
    "distrust",
    "stools",
    "symposia",
    "synagogues",
    "singularities",
    "dead-end situations",
    "skateboards",
    "suffering",
    "breaths",
    "solidity",
    "surprise",
    "smiles",
    "surveillance",
    "suspicion",
    "substance",
    "supports",
    "submarines",
    "submission",
    "overlapping",
    "brushes",
    "brushes",
    "portable speakers",
    "shows",
    "circus shows",
    "show",
    "spices",
    "displacements",
    "sparkling wine",
    "scales",
    "stability",
    "ponds",
    "states",
    "statues",
    "stimuli",
    "roads",
    "layers",
    "toy musical instruments",
    "structuring",
    "astonishment",
    "subordination",
    "success",
    "juices",
    "suggestions",
    "support",
    "entertainment",
    "developments",
    "development",
    "unfolding",
    "carpets",
    "keyboards",
    "camping tables",
    "coffee cups",
    "teacups",
    "baking pans",
    "televisions",
    "temples",
    "leisure",
    "thunderstorms",
    "tenacity",
    "tents",
    "tenderness",
    "tension",
    "tentacles",
    "tequila",
    "thermos",
    "terror",
    "typhoons",
    "tolerance",
    "flashlight",
    "torches",
    "tornadoes",
    "towers",
    "pies",
    "tablecloths",
    "transits",
    "quilts",
    "transformation",
    "transformations",
    "transmissions",
    "tricycles",
    "triumph",
    "sadness",
    "trolley",
    "tsunami",
    "snorkel tubes",
    "thunder",
    "protection",
    "tea",
    "oneness",
    "union",
    "hurricanes",
    "vacation",
    "avalanches",
    "variations",
    "view",
    "views",
    "winds",
    "vegetables",
    "vibrations",
    "dead ends",
    "streets",
    "vigilance",
    "vigor",
    "constraints",
    "wine",
    "vision",
    "life",
    "vitality",
    "victory",
    "liveliness",
    "vodka",
    "flights",
    "voluminosity",
    "swirls",
    "whiskey",
    "workshops",
    "backpacks",
    "paws",
    "fangs",
    "mosquito nets",
  ],
  two: [
    "with the smell of rain",
    "with scent of wild flowers",
    "with golden reflections",
    "with a heartbeat",
    "with a call to nature",
    "with a hidden secret",
    "with a whiff of epic adventure",
    "with an infectious smile",
    "with a silver smile",
    "with a sip of adventure",
    "with a touch of drama",
    "with a touch of elegance",
    "with a touch of madness",
    "with a touch of magic",
    "with a wandering soul",
    "with a poetic soul",
    "with a rebellious soul",
    "with a wild soul",
    "with a caress of serenity",
    "with a note of melancholy",
    "with a note of mystery",
    "with a note of romance",
    "with a brushstroke of color",
    "with a hint of sarcasm",
    "with a trail of adventure",
    "with a splash of magic",
    "with a trace of nostalgia",
    "with dark chocolate",
    "of crystal",
    "of enchanted forest",
    "of fire and ice",
    "of midday",
    "of mystery and suspense",
    "of snow white",
    "of night",
    "of paradise lost",
    "of burning passion",
    "of spring rain",
    "of pure fantasy",
    "of reflection",
    "of awakening",
    "of golden sand",
    "of broken dreams",
    "of dreams",
    "of shooting stars",
    "of impending storm",
    "of darkness and light",
    "of sunset",
    "of golden sunset",
    "of velvet",
    "of intergalactic journey",
    "after a long meditation",
    "during a full moon",
    "during an intergalactic journey",
    "during an aurora borealis",
    "during a yoga class",
    "during a sleepless night",
    "hovering over fate",
    "in vintage style",
    "in a secret workshop",
    "in a moment of pure inspiration",
    "in a world of wonder",
    "in a digital world",
    "in a world where physics is different",
    "in a world where magic is real",
    "in an enchanted world",
    "in a parallel world",
    "in an unknown world",
    "in a realm of spells",
    "in a realm of heavenly light",
    "in a realm of eternal light",
    "in a realm of magic",
    "in a realm of magic and wonders",
    "in a realm of eternal magic",
    "in a fairy realm",
    "in an enchanted realm",
    "in a magical realm",
    "in a lucid dream",
    "in a parallel universe",
    "in an atmosphere of mystery",
    "in a surreal atmosphere",
    "in a forgotten time",
    "in an alternate dimension",
    "while listening to classical music",
    "in the midst of an explosion of colors",
    "in the mind of an alchemist",
    "in the mind of an angel",
    "in the mind of an artist",
    "in the mind of a curious child",
    "in the mind of a druid",
    "in the mind of a celestial being",
    "in the mind of a celestial being",
    "in the mind of a divine being",
    "in the mind of an ethereal being",
    "in the mind of an eternal being",
    "in the mind of a faun",
    "in the mind of a philosopher",
    "in the mind of a madman",
    "in the mind of a healer",
    "in the mind of a visionary inventor",
    "in the mind of a magician",
    "in the mind of a supreme magician",
    "in the mind of a mad mathematician",
    "in the mind of a madman",
    "in the mind of a poet",
    "in the mind of a romantic poet",
    "in the mind of a dreamer",
    "in the mind of a traveler",
    "in the mind of a visionary",
    "in the mind of an ancient deity",
    "in the mind of a celestial deity",
    "in the mind of a sibyl",
    "in the mind of a witch",
    "in the mind of a mad scientist",
    "in the mind of a sorcerer",
    "in the wake of a comet",
    "under the guardian of a shooting star",
    "under the breath of an angel",
    "under the breath of a dragon",
    "under the breath of an elf",
    "under the breath of a unicorn",
    "under the breath of a goddess",
    "under the breath of a deity",
    "under the breath of an ancient deity",
    "under the breath of a nymph",
    "under the breath of a mermaid",
    "under the reflection of a pool of water",
    "under the touch of a fairy",
    "under the light of the setting sun",
    "under the light of the full moon",
    "under the protection of an angel",
    "under a shower of shooting stars",
    "on the crest of a wave",
    "on the crest of a mountain",
    "between the pages of a science fiction book",
  ],
  nerd: [
    "Codemotion",
    "Byte",
    "Pixel",
    "Algoritmo",
    "Code",
    "Debugging",
    "Server",
    "Cloud",
    "Hardware",
    "Software",
    "Hacker",
    "Bit",
    "Firewall",
    "Database",
    "C++",
    "Python",
    "JavaScript",
    "AI (Artificial Intelligence)",
    "Router",
    "Linux",
    "Terminal",
    "Bug",
    "Compiler",
    "Framework",
    "API",
    "GitHub",
    "Encryption",
    "Binary Code",
    "HTML",
    "CSS",
    "IoT (Internet of Things)",
    "Firmware",
    "VR (Virtual Reality)",
    "AR (Augmented Reality)",
    "Blockchain",
    "Cybersecurity",
    "Quantum Computing",
    "SSD",
    "HTTP",
    "FTP",
    "LAN",
    "GUI (Graphical User Interface)",
    "Open Source",
    "Kernel",
    "Emulator",
    "BIOS",
    "Overclocking",
    "Proxy",
    "URL",
    "DNS",
    "Torrent",
  ],
};
