export default {
  languageCode: "es",
  languageName: "Español",
  conjunction: "y",
  one: [
    "ropas",
    "recepción",
    "acumulación",
    "agua mineral",
    "acrobacias",
    "figuras de acción",
    "acceso",
    "aviones",
    "afabilidad",
    "fascinación",
    "afecto",
    "afinidad",
    "ayudantes",
    "alas",
    "alientos",
    "ampliación",
    "alegría",
    "columpios infantiles",
    "balanceo",
    "ambivalencia",
    "hechizo",
    "admiración",
    "amor",
    "amoroso",
    "ángulo",
    "angustia",
    "ansiedad",
    "apariencia",
    "aprobaciones",
    "cometas",
    "arquitecturas",
    "arcoíris",
    "armonía",
    "artes",
    "toallas",
    "jardín de infancia",
    "asambleas",
    "atendientes",
    "subyugación",
    "atención",
    "actos",
    "relevancia",
    "actividad",
    "atracción",
    "actualización",
    "autenticidad",
    "avance",
    "ocurrencias",
    "conciencia",
    "acciones",
    "bailes",
    "danza",
    "muñecas",
    "bancos de niebla",
    "barcos",
    "barreras",
    "basílicas",
    "bajorelieves",
    "baterías de camping",
    "latidos",
    "latidos",
    "baberos",
    "benevolente",
    "bebidas carbonatadas",
    "bicicletas infantiles",
    "cerveza",
    "galletas",
    "bloody mary",
    "burbujas",
    "botellas de agua",
    "bolsas de enfriamiento",
    "brandy",
    "brisas",
    "escarchas",
    "tormentas de nieve",
    "burbon",
    "brújula",
    "bustos",
    "café",
    "caipirinha",
    "calor",
    "cambios",
    "canoas",
    "caramelos",
    "carácter",
    "cargadores portátiles",
    "adorabilidad",
    "carne",
    "carros",
    "casitas de juego",
    "casos",
    "castillos",
    "catamaranes",
    "catedrales",
    "cables USB",
    "celebración",
    "champán",
    "iglesias",
    "techos",
    "ciclón",
    "cinturones",
    "chocolate",
    "cuencos",
    "circunstancias",
    "mechones",
    "hilos",
    "adjuvantes",
    "cocteles",
    "consistencia",
    "cognac",
    "cogniciones",
    "coincidencia",
    "colaboradores",
    "colaboración",
    "collares",
    "entrevistas",
    "cuchillos",
    "comportamientos",
    "comprensión",
    "comprensión",
    "entendimientos",
    "comunicación",
    "comunicaciones",
    "hermandad",
    "conciertos",
    "conceptos",
    "conclusión",
    "acuerdo",
    "concretización",
    "condimentos",
    "compartición",
    "condiciones",
    "conferencias",
    "conformidad",
    "confusión",
    "conocimiento",
    "conciencia",
    "consecuencias",
    "preservación",
    "consistencia",
    "contenedores herméticos",
    "continuidad",
    "contradicción",
    "controles",
    "convenciones",
    "convergencia",
    "conversaciones",
    "cooperación",
    "mantas",
    "fundas de edredón",
    "cuerdas para saltar",
    "amabilidad",
    "cuernos",
    "corporativización",
    "corrientes",
    "carriles",
    "cosmopolita",
    "constancia",
    "construcción",
    "construcciones",
    "creación",
    "cremas",
    "crecimiento",
    "crestas",
    "cucharas",
    "tapones",
    "montones",
    "curiosidades",
    "almohadas",
    "almohadas decorativas",
    "almohadas inflables",
    "almohadas para mascotas",
    "almacenamiento",
    "daiquiri",
    "danza",
    "delicadeza",
    "decepción",
    "diálogos",
    "debates",
    "declaración",
    "dilatación",
    "dilución",
    "adicción",
    "pinturas",
    "direcciones",
    "discernimientos",
    "disciplina",
    "discusiones",
    "dibujos",
    "desilusión",
    "desesperación",
    "diversión",
    "dulzura",
    "pena",
    "dudas",
    "durabilidad",
    "dureza",
    "edificios",
    "efectos",
    "elefantes",
    "helicópteros",
    "emanaciones",
    "emergencia",
    "emoción",
    "empatía",
    "energía",
    "hierbas",
    "actuaciones",
    "existencia",
    "resultado",
    "expansión",
    "exploración",
    "exposiciones",
    "expresión",
    "expresiones",
    "esencia",
    "éxtasis",
    "euforia",
    "eventos",
    "evolución",
    "evoluciones",
    "fascinación",
    "hechos",
    "felicidad",
    "fenómenos",
    "firmeza",
    "celebración",
    "llamas",
    "flores",
    "flujos",
    "fluctuaciones",
    "electrocución",
    "rayos",
    "tenedores",
    "quesos",
    "formación",
    "hornillo de camping",
    "fortaleza",
    "fortalezas",
    "fuerza",
    "fotografías",
    "deslizamientos de tierra",
    "frescura",
    "frisbee",
    "frutas",
    "escape",
    "rayos",
    "túneles",
    "escarchas",
    "escarchas",
    "generación",
    "amabilidad",
    "genuinidad",
    "gestos",
    "ginebra",
    "gin tonic",
    "juguetes",
    "juguetes educativos",
    "juegos",
    "alegría",
    "juventud",
    "jirafas",
    "gloria",
    "gotas",
    "gotitas",
    "gomitas",
    "graffiti",
    "granizo",
    "rejillas de camping",
    "guardián",
    "búhos",
    "guía",
    "aficiones",
    "ideas",
    "identidad",
    "iluminaciones",
    "ilustraciones",
    "imágenes",
    "callejones sin salida",
    "impedimentos",
    "encantamiento",
    "encarnación",
    "incentivos",
    "incertidumbre",
    "incitaciones",
    "encuentros",
    "indagación",
    "indecisión",
    "indicación",
    "direcciones",
    "inferioridad",
    "inflación",
    "ampliación",
    "ampliación",
    "inhibiciones",
    "integridad",
    "interacciones",
    "interés",
    "intereses",
    "intercambios",
    "intimidad",
    "entretenimiento",
    "perspectivas",
    "invención",
    "café irlandés",
    "irradiaciones",
    "inspiraciones",
    "kayaks",
    "lagos",
    "lagunas",
    "lámparas",
    "destellos",
    "faroles",
    "sábanas",
    "leones",
    "límites",
    "candados",
    "luces de camping",
    "autos de juguete",
    "manifestación",
    "mantenimiento",
    "mareas",
    "margarita",
    "mares",
    "martinis",
    "máscaras",
    "máscaras de buceo",
    "colchones",
    "colchones",
    "materialización",
    "lápices",
    "memoriales",
    "asombro",
    "mejora",
    "migraciones",
    "patrones",
    "mojitos",
    "multiplicación",
    "scooters",
    "monumentos",
    "mezquitas",
    "moscow mule",
    "exposiciones",
    "motivaciones",
    "ratón",
    "movimientos",
    "movimientos rotatorios",
    "museos",
    "mutaciones",
    "mutualidad",
    "nacimiento",
    "naturaleza",
    "naturalidad muerta",
    "neblinas",
    "negroni",
    "nerviosismo",
    "nieve",
    "nevada",
    "estandarización",
    "nubes",
    "desnudez",
    "números",
    "obediencia",
    "océanos",
    "paraguas",
    "paraguas",
    "olas",
    "obras",
    "oposición",
    "organización",
    "orientaciones",
    "originalidad",
    "horizonte",
    "oscilaciones",
    "observación",
    "obstáculos",
    "resultado",
    "paddle board",
    "sartenes",
    "paisajes",
    "paisaje",
    "edificios",
    "pelotas",
    "pelotas de playa",
    "pantanos",
    "pan",
    "panorama",
    "panoramas",
    "pantalones",
    "zapatillas",
    "pelucas",
    "pasajes",
    "pasatiempos",
    "pasión",
    "pasta",
    "patines en línea",
    "miedo",
    "cabellos",
    "pieles",
    "peluches",
    "marcadores",
    "ollas",
    "percepción",
    "percepciones",
    "rendimiento",
    "permanencia",
    "perplejidad",
    "persistencia",
    "personalidad",
    "pescado",
    "placer",
    "plantas",
    "platos",
    "pina colada",
    "aletas",
    "lluvias",
    "pistolas de agua",
    "pinturas",
    "plumas",
    "acolchados",
    "utensilios de camping",
    "preocupación",
    "presencia",
    "preservación",
    "procesos",
    "procesos",
    "procreación",
    "progreso",
    "progreso",
    "prosecco",
    "perspectiva",
    "proximidad",
    "protección",
    "pulso",
    "punto de referencia",
    "punto de vista",
    "rompecabezas",
    "marco",
    "reuniones",
    "ranas",
    "representaciones",
    "reseñas",
    "realización",
    "reacciones",
    "reciprocidad",
    "recitales",
    "recitales",
    "regulación",
    "relajación",
    "relajación",
    "repelentes de insectos",
    "represiones",
    "resiliencia",
    "resiliencia",
    "respiración",
    "restituciones",
    "restricciones",
    "retroalimentación",
    "búsqueda",
    "reconocimiento",
    "recreación",
    "reflexiones",
    "refugio",
    "regeneración",
    "rigidez",
    "renacimiento",
    "renovación",
    "descanso",
    "reproducción",
    "risa",
    "reserva",
    "risa",
    "respuestas",
    "resultados",
    "regresos",
    "retratos",
    "reuniones",
    "revelación",
    "robustez",
    "rotaciones",
    "rocíos",
    "ron",
    "sacos de dormir",
    "sabidurías",
    "sake",
    "salsas",
    "protección",
    "santuarios",
    "santuario",
    "jabones",
    "intercambios",
    "cajas",
    "paisajes",
    "escenas",
    "escepticismo",
    "chistes",
    "ataduras",
    "bufandas",
    "chispas",
    "resbaladillas para bebés",
    "desconcertante",
    "descubrimiento",
    "abreviación",
    "whisky",
    "esculturas",
    "cubos y palas de playa",
    "sillas",
    "sillas de camping",
    "señalización",
    "signo",
    "seminarios",
    "sensación",
    "sensibilidad",
    "sensualidad",
    "caminos",
    "sentimiento",
    "ataduras",
    "desconfianza",
    "taburetes",
    "simposios",
    "sinagogas",
    "singularidades",
    "situaciones sin salida",
    "skateboards",
    "sufrimiento",
    "alientos",
    "solidez",
    "sorpresa",
    "sonrisas",
    "vigilancia",
    "sospecha",
    "sustancia",
    "soportes",
    "submarinos",
    "sumisión",
    "superposición",
    "cepillos",
    "cepillos",
    "altavoces portátiles",
    "espectáculos",
    "espectáculos de circo",
    "espectáculo",
    "especias",
    "desplazamientos",
    "vino espumoso",
    "balanzas",
    "estabilidad",
    "estanques",
    "estados",
    "estatuas",
    "estímulos",
    "carreteras",
    "capas",
    "instrumentos musicales de juguete",
    "estructuración",
    "asombro",
    "subordinación",
    "éxito",
    "jugos",
    "sugerencias",
    "apoyo",
    "entretenimiento",
    "desarrollos",
    "desarrollo",
    "despliegue",
    "alfombras",
    "teclados",
    "mesas de camping",
    "tazas de café",
    "tazas de té",
    "bandejas para hornear",
    "televisores",
    "templos",
    "ocio",
    "tormentas",
    "tenacidad",
    "tiendas",
    "ternura",
    "tensión",
    "tentáculos",
    "tequila",
    "termos",
    "terror",
    "tifones",
    "tolerancia",
    "linterna",
    "antorchas",
    "tornados",
    "torres",
    "pasteles",
    "manteles",
    "tránsitos",
    "acolchados",
    "transformación",
    "transformaciones",
    "transmisiones",
    "triciclos",
    "triunfo",
    "tristeza",
    "carro",
    "tsunami",
    "tubos de snorkel",
    "trueno",
    "protección",
    "té",
    "unicidad",
    "unión",
    "huracanes",
    "vacaciones",
    "aludes",
    "variaciones",
    "vista",
    "vistas",
    "vientos",
    "vegetales",
    "vibraciones",
    "callejones sin salida",
    "calles",
    "vigilancia",
    "vigor",
    "restricciones",
    "vino",
    "visión",
    "vida",
    "vitalidad",
    "victoria",
    "vivacidad",
    "vodka",
    "vuelos",
    "voluminosidad",
    "remolinos",
    "whisky",
    "talleres",
    "mochilas",
    "patas",
    "colmillos",
    "mosquiteros",
  ],
  two: [
    "con el olor a lluvia",
    "con el aroma de flores silvestres",
    "con reflejos dorados",
    "con un latido",
    "con una llamada a la naturaleza",
    "con un secreto oculto",
    "con un atisbo de aventura épica",
    "con una sonrisa contagiosa",
    "con una sonrisa plateada",
    "con un sorbo de aventura",
    "con un toque de drama",
    "con un toque de elegancia",
    "con un toque de locura",
    "con un toque de magia",
    "con un alma errante",
    "con un alma poética",
    "con un alma rebelde",
    "con un alma salvaje",
    "con una caricia de serenidad",
    "con una nota de melancolía",
    "con una nota de misterio",
    "con una nota de romance",
    "con una pincelada de color",
    "con un atisbo de sarcasmo",
    "con una estela de aventura",
    "con un toque de magia",
    "con un rastro de nostalgia",
    "con chocolate negro",
    "de cristal",
    "de bosque encantado",
    "de fuego y hielo",
    "de mediodía",
    "de misterio y suspense",
    "de blanco nieve",
    "de noche",
    "de paraíso perdido",
    "de pasión ardiente",
    "de lluvia de primavera",
    "de pura fantasía",
    "de reflexión",
    "de despertar",
    "de arena dorada",
    "de sueños rotos",
    "de sueños",
    "de estrellas fugaces",
    "de tormenta inminente",
    "de oscuridad y luz",
    "de atardecer",
    "de atardecer dorado",
    "de terciopelo",
    "de viaje intergaláctico",
    "tras una larga meditación",
    "durante una luna llena",
    "durante un viaje intergaláctico",
    "durante una aurora boreal",
    "durante una clase de yoga",
    "durante una noche sin dormir",
    "suspendido sobre el destino",
    "en estilo vintage",
    "en un taller secreto",
    "en un momento de pura inspiración",
    "en un mundo de maravillas",
    "en un mundo digital",
    "en un mundo donde la física es diferente",
    "en un mundo donde la magia es real",
    "en un mundo encantado",
    "en un mundo paralelo",
    "en un mundo desconocido",
    "en un reino de hechizos",
    "en un reino de luz celestial",
    "en un reino de luz eterna",
    "en un reino de magia",
    "en un reino de magia y maravillas",
    "en un reino de magia eterna",
    "en un reino de hadas",
    "en un reino encantado",
    "en un reino mágico",
    "en un sueño lúcido",
    "en un universo paralelo",
    "en una atmósfera de misterio",
    "en una atmósfera surrealista",
    "en un tiempo olvidado",
    "en una dimensión alterna",
    "mientras escuchas música clásica",
    "en medio de una explosión de colores",
    "en la mente de un alquimista",
    "en la mente de un ángel",
    "en la mente de un artista",
    "en la mente de un niño curioso",
    "en la mente de un druida",
    "en la mente de un ser celestial",
    "en la mente de un ser celestial",
    "en la mente de un ser divino",
    "en la mente de un ser etéreo",
    "en la mente de un ser eterno",
    "en la mente de un fauno",
    "en la mente de un filósofo",
    "en la mente de un loco",
    "en la mente de un sanador",
    "en la mente de un inventor visionario",
    "en la mente de un mago",
    "en la mente de un mago supremo",
    "en la mente de un matemático loco",
    "en la mente de un loco",
    "en la mente de un poeta",
    "en la mente de un poeta romántico",
    "en la mente de un soñador",
    "en la mente de un viajero",
    "en la mente de un visionario",
    "en la mente de una deidad antigua",
    "en la mente de una deidad celestial",
    "en la mente de una sibila",
    "en la mente de una bruja",
    "en la mente de un científico loco",
    "en la mente de un hechicero",
    "a la estela de un cometa",
    "bajo la guardia de una estrella fugaz",
    "bajo el aliento de un ángel",
    "bajo el aliento de un dragón",
    "bajo el aliento de un elfo",
    "bajo el aliento de un unicornio",
    "bajo el aliento de una diosa",
    "bajo el aliento de una deidad",
    "bajo el aliento de una deidad antigua",
    "bajo el aliento de una ninfa",
    "bajo el aliento de una sirena",
    "bajo el reflejo de un charco de agua",
    "bajo el toque de un hada",
    "bajo la luz del sol poniente",
    "bajo la luz de la luna llena",
    "bajo la protección de un ángel",
    "bajo una lluvia de estrellas fugaces",
    "en la cresta de una ola",
    "en la cresta de una montaña",
    "entre las páginas de un libro de ciencia ficción",
  ],
  nerd: [
    "Codemotion",
    "Byte",
    "Pixel",
    "Algoritmo",
    "Código",
    "Depuración",
    "Servidor",
    "Nube",
    "Hardware",
    "Software",
    "Hacker",
    "Bit",
    "Cortafuegos",
    "Base de datos",
    "C++",
    "Python",
    "JavaScript",
    "IA (Inteligencia Artificial)",
    "Router",
    "Linux",
    "Terminal",
    "Error",
    "Compilador",
    "Framework",
    "API",
    "GitHub",
    "Cifrado",
    "Binario",
    "HTML",
    "CSS",
    "IoT (Internet de las Cosas)",
    "Firmware",
    "VR (Realidad Virtual)",
    "AR (Realidad Aumentada)",
    "Blockchain",
    "Ciberseguridad",
    "Computación Cuántica",
    "SSD",
    "HTTP",
    "FTP",
    "LAN",
    "GUI (Interfaz Gráfica de Usuario)",
    "Código Abierto",
    "Kernel",
    "Emulador",
    "BIOS",
    "Overclocking",
    "Proxy",
    "URL",
    "DNS",
    "Torrent",
  ],
};