export default {
  languageCode: "es",
  languageName: "Español",
  conjunction: "y",
  one: [
    "túnicas",
    "recepción",
    "acumulación",
    "agua mineral",
    "acrobacias",
    "figuras de acción",
    "adhesión",
    "aviones",
    "afecto",
    "afinidad",
    "ayudantes",
    "alas",
    "alientos",
    "alegría",
    "columpios",
    "admiración",
    "amor",
    "ángulo",
    "angustia",
    "ansiedad",
    "apariencia",
    "cometas",
    "arquitecturas",
    "arco iris",
    "armonía",
    "artes",
    "toallas",
    "jardín de infancia",
    "asambleas",
    "asistentes",
    "atención",
    "actividades",
    "atracción",
    "autenticidad",
    "avance",
    "acontecimientos",
    "conciencia",
    "acciones",
    "danzas",
    "baile",
    "muñecas",
    "bancos de niebla",
    "barcos",
    "barreras",
    "basílicas",
    "bajorrelieves",
    "latidos",
    "baberos",
    "bebidas gaseosas",
    "bicicletas",
    "cerveza",
    "galletas",
    "bloody mary",
    "burbujas",
    "botellas de agua",
    "bolsas refrigerantes",
    "brandy",
    "brisas",
    "ventiscas",
    "burbujas",
    "brújula",
    "bustos",
    "café",
    "caipirinha",
    "calor",
    "cambios",
    "canoas",
    "caramelo",
    "carácter",
    "cargadores portátiles",
    "carne",
    "carritos",
    "castillos",
    "catedrales",
    "cables usb",
    "celebración",
    "champán",
    "iglesias",
    "marquesinas",
    "ciclón",
    "cinturones",
    "chocolate",
    "cuencos",
    "cócteles",
    "consistencia",
    "coincidencia",
    "colaboradores",
    "colaboración",
    "collares",
    "entrevistas",
    "cuchillos",
    "comprensión",
    "comprensión",
    "comunicación",
    "compañerismo",
    "conciertos",
    "conceptos",
    "conclusión",
    "concordia",
    "condimentos",
    "compartir",
    "condiciones",
    "conferencias",
    "confusión",
    "conocimiento",
    "consecuencias",
    "conservación",
    "consistencia",
    "recipientes herméticos",
    "continuidad",
    "contradicción",
    "controles",
    "convenciones",
    "convergencia",
    "conversaciones",
    "cooperación",
    "mantas",
    "fundas de edredón",
    "cuerdas para saltar",
    "cuernos",
    "corrientes",
    "carriles",
    "constancia",
    "construcción",
    "construcciones",
    "creación",
    "cremas",
    "crecimiento",
    "crestas",
    "cucharas",
    "auriculares",
    "curiosidades",
    "almohadas",
    "caso",
    "baile",
    "delicadeza",
    "decepción",
    "diálogos",
    "debates",
    "declaración",
    "aficionados",
    "adicción",
    "pinturas",
    "direcciones",
    "disciplina",
    "discusiones",
    "dibujos",
    "desesperación",
    "diversión",
    "dulzura",
    "tristeza",
    "dudas",
    "durabilidad",
    "dureza",
    "edificios",
    "efectos",
    "elefantes",
    "helicópteros",
    "emergencia",
    "emoción",
    "empatía",
    "energía",
    "hierbas",
    "actuaciones",
    "existencia",
    "resultado",
    "expansión",
    "exploración",
    "exposiciones",
    "expresión",
    "expresiones",
    "esencia",
    "éxtasis",
    "euforia",
    "acontecimientos",
    "evolución",
    "hechos",
    "felicidad",
    "fenómenos",
    "firmeza",
    "celebración",
    "flores",
    "tenedores",
    "quesos",
    "formación",
    "estufa de campamento",
    "fortaleza",
    "fortaleza",
    "fotografías",
    "derrumbes",
    "frescura",
    "frisbee",
    "fruta",
    "fuga",
    "relámpago",
    "túneles",
    "helado",
    "generación",
    "amabilidad",
    "gestos",
    "ginebra",
    "juguetes",
    "juguetes educativos",
    "juegos",
    "alegría",
    "juventud",
    "jirafas",
    "gloria",
    "gotas",
    "gotas",
    "gominolas",
    "graffiti",
    "granizo",
    "rejillas",
    "guardia",
    "búhos",
    "guía",
    "aficiones",
    "ideas",
    "identidad",
    "iluminaciones",
    "ilustraciones",
    "imágenes",
    "impedimentos",
    "encantamiento",
    "encarnación",
    "incentivos",
    "incertidumbre",
    "incitaciones",
    "encuentros",
    "indagación",
    "indecisión",
    "direcciones",
    "inferioridad",
    "ampliación",
    "ampliación",
    "inhibiciones",
    "integridad",
    "interacciones",
    "interés",
    "intereses",
    "intimidad",
    "entretenimiento",
    "perspicacia",
    "invención",
    "irradiaciones",
    "inspiraciones",
    "kayaks",
    "lagos",
    "lagunas",
    "lámparas",
    "destellos",
    "linternas",
    "sábanas",
    "leones",
    "límites",
    "candados",
    "luces",
    "coches de juguete",
    "manifestación",
    "mantenimiento",
    "mares",
    "máscaras",
    "colchones",
    "esteras",
    "lápices",
    "maravilla",
    "mejora",
    "migraciones",
    "patrones",
    "multiplicación",
    "scooters",
    "monumentos",
    "mezquitas",
    "exposiciones",
    "motivaciones",
    "ratones",
    "movimientos",
    "movimientos de rotación",
    "museos",
    "mutaciones",
    "nacimiento",
    "naturaleza",
    "nerviosismo",
    "nieve",
    "nevada",
    "nubes",
    "desnudez",
    "números",
    "océanos",
    "paraguas",
    "paraguas",
    "olas",
    "obras",
    "oposición",
    "organización",
    "originalidad",
    "horizonte",
    "oscilaciones",
    "observación",
    "obstáculos",
    "cacerolas",
    "paisajes",
    "edificios",
    "bolas",
    "pantanos",
    "pan",
    "panorama",
    "pantalones",
    "zapatillas",
    "pelucas",
    "pasajes",
    "pasatiempos",
    "pasión",
    "pasta",
    "patines",
    "miedo",
    "pelos",
    "pieles",
    "peluches",
    "marcadores",
    "ollas",
    "percepción",
    "rendimiento",
    "personalidad",
    "pescado",
    "placer",
    "plantas",
    "platos",
    "aletas",
    "lluvias",
    "pistolas de agua",
    "pinturas",
    "plumas",
    "edredones",
    "cubiertos",
    "preocupación",
    "presencia",
    "procesos",
    "progreso",
    "protección",
    "punto de vista",
    "rompecabezas",
    "marco",
    "reuniones",
    "ranas",
    "representaciones",
    "realización",
    "reacciones",
    "juegos",
    "regulación",
    "relajación",
    "repelentes de insectos",
    "resistencia",
    "respiración",
    "restricciones",
    "investigación",
    "reconocimiento",
    "recreación",
    "reflexiones",
    "refugio",
    "renacimiento",
    "descanso",
    "reproducción",
    "risa",
    "reserva",
    "risa",
    "respuestas",
    "resultados",
    "retratos",
    "reuniones",
    "sacos de dormir",
    "sabiduría",
    "salsas",
    "conservación",
    "santuarios",
    "jabones",
    "intercambios",
    "cajas",
    "escenas",
    "escepticismo",
    "bromas",
    "bondage",
    "bufandas",
    "chispas",
    "diapositivas",
    "descubrimiento",
    "whisky",
    "esculturas",
    "cubos",
    "sillas",
    "signo",
    "seminarios",
    "sensación",
    "sensación",
    "caminos",
    "sensación",
    "taburetes",
    "monopatines",
    "sufrimiento",
    "solidez",
    "sorpresa",
    "sonrisas",
    "vigilancia",
    "sospecha",
    "sustancia",
    "soportes",
    "submarinos",
    "superposición",
    "cepillos",
    "altavoces portátiles",
    "espectáculos",
    "vino espumoso",
    "escalas",
    "estanques",
    "estatuas",
    "estímulos",
    "carreteras",
    "capas",
    "instrumentos musicales",
    "asombro",
    "éxito",
    "jugos",
    "sugerencias",
    "apoyo",
    "entretenimiento",
    "desarrollo",
    "alfombras",
    "teclados",
    "mesas",
    "tazas",
    "sartenes",
    "televisores",
    "ocio",
    "tormentas",
    "tiendas",
    "tentáculos",
    "termos",
    "terror",
    "tifones",
    "linterna",
    "tornados",
    "torres",
    "pasteles",
    "manteles",
    "edredones",
    "transformación",
    "triciclos",
    "triunfo",
    "tristeza",
    "tsunami",
    "trueno",
    "té",
    "unión",
    "vacaciones",
    "avalanchas",
    "variaciones",
    "vientos",
    "vegetales",
    "vibraciones",
    "rutas",
    "vigilancia",
    "limitaciones",
    "vino",
    "vida",
    "victoria",
    "vuelos",
    "talleres",
    "mochilas",
    "patas",
    "colmillos",
    "mosquiteras",
  ],
  two: [
    "con una llamada a la naturaleza",
    "con un secreto oculto",
    "con un tufillo de aventura épica",
    "con una sonrisa contagiosa",
    "con un sorbo de aventura",
    "con un toque de drama",
    "con un toque de elegancia",
    "con un toque de locura",
    "con un toque de magia",
    "con alma aventurera",
    "con alma poética",
    "con alma rebelde",
    "con un alma salvaje",
    "con una caricia de serenidad",
    "con una nota de melancolía",
    "con una nota de misterio",
    "con una nota de romanticismo",
    "con una pizca de sarcasmo",
    "con un toque de magia",
    "con una pizca de nostalgia",
    "con chocolate negro",
    "de cristal",
    "de fuego y hielo",
    "con un toque de misterio y suspense",
    "de noche",
    "de pura fantasía",
    "en la oscuridad",
    "de sueños rotos",
    "en un sueño",
    "después de una larga meditación",
    "durante una luna llena",
    "durante un viaje intergaláctico",
    "durante una clase de yoga",
    "durante una noche de insomnio",
    "en estilo vintage",
    "en un laboratorio secreto",
    "en un libro de Pirandello",
    "en Nápoles",
    "en un mundo digital",
    "en un mundo donde la gravedad es diferente",
    "en un mundo donde la magia es real",
    "en un mundo encantado",
    "en un mundo paralelo",
    "en un mundo desconocido",
    "en un reino de hadas",
    "en un universo paralelo",
    "en una atmósfera surrealista",
    "en una dimensión alternativa",
    "mientras escucho música clásica",
    "en la mente de un informático",
    "en la mente de un artista",
    "en la mente de un niño",
    "en la mente de un gerente",
    "en la mente de un ser eterno",
    "en la mente de un filósofo",
    "en la mente de un loco",
    "en la mente de un curandero",
    "en la mente de un mago",
    "en la mente de un matemático loco",
    "en la mente de un poeta",
    "en la mente de un poeta romántico",
    "en la mente de un soñador",
    "en la mente de un viajero",
    "en la mente de un visionario",
    "en la mente de una antigua deidad",
    "en la mente de una bruja",
    "en la mente de un científico loco",
    "en la mente de un hechicero",
    "bajo el aliento de un unicornio",
    "bajo el reflejo de un estanque de agua",
    "bajo el toque de un hada",
    "bajo la luz del sol poniente",
    "bajo la luz de la luna llena",
    "bajo una lluvia de estrellas fugaces",
    "entre las páginas de un libro de ciencia ficción",
    "en Hogwarts",
    "en la biblioteca",
    "en el cine",
    "si lo anunciara Apple",
    "en blanco y negro",
    "en 3024",
  ],
  nerd: [
    "Codemotion",
    "Byte",
    "Pixel",
    "Algoritmo",
    "Código",
    "Depuración",
    "Servidor",
    "Nube",
    "Hardware",
    "Software",
    "Hacker",
    "Bit",
    "Cortafuegos",
    "Base de datos",
    "C++",
    "Python",
    "JavaScript",
    "AI",
    "Router",
    "Linux",
    "Terminal",
    "Error",
    "Compilador",
    "Framework",
    "API",
    "GitHub",
    "Cifrado",
    "Binario",
    "HTML",
    "CSS",
    "IoT (Internet de las Cosas)",
    "Firmware",
    "VR (Realidad Virtual)",
    "AR (Realidad Aumentada)",
    "Blockchain",
    "Ciberseguridad",
    "Computación Cuántica",
    "SSD",
    "HTTP",
    "FTP",
    "LAN",
    "GUI (Interfaz Gráfica de Usuario)",
    "Código Abierto",
    "Kernel",
    "Emulador",
    "BIOS",
    "Overclocking",
    "Proxy",
    "URL",
    "DNS",
    "Torrent",
    "Browser",
    "VPN",
  ],
};
