export default {
  languageCode: "it",
  languageName: "Italiano",
  conjunction: "e",
  one: [
    "accappatoi",
    "accoglienza",
    "accumulo",
    "acqua minerale",
    "acrobazie",
    "action figure",
    "adesione",
    "aerei",
    "affabilità",
    "affascinamento",
    "affetto",
    "affinità",
    "aiutanti",
    "ali",
    "aliti",
    "allargamento",
    "allegria",
    "altalene per bambini",
    "altorilievi",
    "ambivalenza",
    "ammaliamento",
    "ammirazione",
    "amore",
    "amorevole",
    "angolazione",
    "angoscia",
    "ansia",
    "apparizione",
    "appoggi",
    "aquiloni",
    "architetture",
    "arcobaleni",
    "armonia",
    "arti",
    "asciugamani",
    "asilo",
    "assemblee",
    "assistenti",
    "assoggettamento",
    "attenzione",
    "atti",
    "attinenza",
    "attività",
    "attrazione",
    "attualizzazione",
    "autenticità",
    "avanzamento",
    "avvenimenti",
    "awareness",
    "azioni",
    "balletti",
    "ballo",
    "bambole",
    "banchi di nebbia",
    "barche",
    "barriere",
    "basiliche",
    "bassorilievi",
    "batterie da campeggio",
    "battiti",
    "battute",
    "bavaglini",
    "benevolo",
    "bevande gassate",
    "biciclette per bambini",
    "birra",
    "biscotti",
    "bloody mary",
    "bolle",
    "borracce",
    "borse termiche",
    "brandy",
    "brezze",
    "brine",
    "bufere",
    "burbon",
    "bussola",
    "busti",
    "caffè",
    "caipirinha",
    "calore",
    "cambiamenti",
    "canoe",
    "caramelle",
    "carattere",
    "caricabatterie portatili",
    "carineria",
    "carne",
    "carrelli",
    "casette per bambini",
    "casi",
    "castelli",
    "catamarani",
    "cattedrali",
    "cavi usb",
    "celebrazione",
    "champagne",
    "chiese",
    "chiome",
    "ciclone",
    "cinture",
    "cioccolata",
    "ciotole",
    "circostanze",
    "ciuffetti",
    "ciuffi",
    "coadiuvanti",
    "cocktail",
    "coerenza",
    "cognac",
    "cognizioni",
    "coincidenza",
    "collaboratori",
    "collaborazione",
    "collari",
    "colloqui",
    "coltelli",
    "comportamenti",
    "comprendere",
    "comprensione",
    "comprensioni",
    "comunicazione",
    "comunicazioni",
    "comunione",
    "concerti",
    "concetti",
    "conclusione",
    "concordia",
    "concretizzazione",
    "condimenti",
    "condivisione",
    "condizioni",
    "conferenze",
    "conformità",
    "confusione",
    "conoscenza",
    "consciousness",
    "conseguenze",
    "conservazione",
    "consistenza",
    "contenitori ermetici",
    "continuità",
    "contraddizione",
    "controlli",
    "convegni",
    "convergenza",
    "conversazioni",
    "cooperazione",
    "coperte",
    "copripiumini",
    "corde per saltare",
    "cordialità",
    "corna",
    "corporificazione",
    "correnti",
    "corsie",
    "cosmopolitan",
    "costanza",
    "costruzione",
    "costruzioni",
    "creazione",
    "creme",
    "crescita",
    "creste",
    "cucchiai",
    "cuffie",
    "cumuli",
    "curiosità",
    "cuscini",
    "cuscini decorativi",
    "cuscini gonfiabili",
    "cuscini per animali domestici",
    "custodia",
    "daiquiri",
    "danza",
    "delicatezza",
    "delusione",
    "dialoghi",
    "dibattiti",
    "dichiarazione",
    "dilatazione",
    "dilettanti",
    "dipendenza",
    "dipinti",
    "direzioni",
    "discernimenti",
    "disciplina",
    "discussioni",
    "disegni",
    "disillusione",
    "disperazione",
    "divertimento",
    "dolcezza",
    "dolore",
    "dubbi",
    "durata",
    "durezza",
    "edifici",
    "effetti",
    "elefanti",
    "elicotteri",
    "emanazioni",
    "emergenza",
    "emozione",
    "empatia",
    "energia",
    "erbe aromatiche",
    "esibizioni",
    "esistenza",
    "esito",
    "espansione",
    "esplorazione",
    "esposizioni",
    "espressione",
    "espressioni",
    "essenza",
    "estasi",
    "euforia",
    "eventi",
    "evoluzione",
    "evoluzioni",
    "fascinazione",
    "fatti",
    "felicità",
    "fenomeni",
    "fermezza",
    "festa",
    "fiammate",
    "fiori",
    "flussi",
    "fluttuazioni",
    "folgorazione",
    "folgori",
    "forchette",
    "formaggi",
    "formazione",
    "fornelli da campeggio",
    "fortezza",
    "fortezze",
    "forza",
    "fotografie",
    "frane",
    "freschezza",
    "frisbee",
    "frutta",
    "fuga",
    "fulmini",
    "gallerie",
    "gelate",
    "gelati",
    "generazione",
    "gentilezza",
    "genuinità",
    "gesti",
    "gin",
    "gin tonic",
    "giocattoli",
    "giocattoli educativi",
    "giochi",
    "gioia",
    "gioventù",
    "giraffe",
    "gloria",
    "gocce",
    "goccioline",
    "gommoni",
    "graffiti",
    "grandine",
    "griglie da campeggio",
    "guardia",
    "gufi",
    "guida",
    "hobby",
    "idee",
    "identità",
    "illuminazioni",
    "illustrazioni",
    "immagini",
    "impasse",
    "impedimenti",
    "incanto",
    "incarnazione",
    "incentivi",
    "incertezza",
    "incitamenti",
    "incontri",
    "indagine",
    "indecisione",
    "indicazione",
    "indicazioni",
    "inferiorità",
    "inflazione",
    "ingrandimento",
    "ingrossamento",
    "inibizioni",
    "integrità",
    "interazioni",
    "interesse",
    "interessi",
    "interscambi",
    "intimità",
    "intrattenimento",
    "intuizioni",
    "invenzione",
    "irish coffee",
    "irradiazioni",
    "ispirazioni",
    "kayak",
    "laghi",
    "lagune",
    "lampade",
    "lampi",
    "lanterne",
    "lenzuola",
    "leoni",
    "limiti",
    "lucchetti",
    "luci da campeggio",
    "macchinine",
    "manifestazione",
    "mantenimento",
    "maree",
    "margarita",
    "mari",
    "martini",
    "maschere",
    "maschere da sub",
    "materassi",
    "materassini",
    "materializzazione",
    "matite",
    "memoriali",
    "meraviglia",
    "miglioramento",
    "migrazioni",
    "modelli",
    "mojito",
    "moltiplicazione",
    "monopattini",
    "monumenti",
    "moschee",
    "moscow mule",
    "mostre",
    "motivazioni",
    "mouse",
    "movimenti",
    "movimenti rotatori",
    "musei",
    "mutazioni",
    "mutualità",
    "nascita",
    "natura",
    "naturalezze morte",
    "nebbie",
    "negroni",
    "nervosismo",
    "neve",
    "nevicate",
    "normazione",
    "nubi",
    "nudi",
    "numeri",
    "obbedienza",
    "oceani",
    "ombrelli",
    "ombrelloni",
    "onde",
    "opere",
    "opposizione",
    "organizzazione",
    "orientamenti",
    "originalità",
    "orizzonte",
    "oscillazioni",
    "osservazione",
    "ostacoli",
    "outcome",
    "paddle board",
    "padelle",
    "paesaggi",
    "paesaggio",
    "palazzi",
    "palloni",
    "palloni da spiaggia",
    "paludi",
    "pane",
    "panorama",
    "panorami",
    "pantaloni",
    "pantofole",
    "parrucche",
    "passaggi",
    "passatempi",
    "passione",
    "pasta",
    "pattini a rotelle",
    "paura",
    "peli",
    "pellicce",
    "peluche",
    "pennarelli",
    "pentole",
    "percezione",
    "percezioni",
    "performance",
    "permanenza",
    "perplessità",
    "persistenza",
    "personalità",
    "pesci",
    "piacere",
    "piante",
    "piatti",
    "pina colada",
    "pinne",
    "piogge",
    "pistole ad acqua",
    "pitture",
    "piume",
    "piumini",
    "posate da campeggio",
    "preoccupazione",
    "presenza",
    "preservazione",
    "procedimenti",
    "processi",
    "procreazione",
    "progressi",
    "progresso",
    "prosecco",
    "prospettiva",
    "prossimità",
    "protezione",
    "pulsazioni",
    "punto di riferimento",
    "punto di vista",
    "puzzle",
    "quadro",
    "raduni",
    "rane",
    "rappresentazioni",
    "rassegne",
    "realizzazione",
    "reazioni",
    "reciprocità",
    "recital",
    "recite",
    "regolamentazione",
    "relax",
    "relax",
    "repellenti per insetti",
    "repressioni",
    "resilienza",
    "resistenza",
    "respiro",
    "restituzioni",
    "restrizioni",
    "retroazioni",
    "ricerca",
    "riconoscimento",
    "ricreazione",
    "riflessi",
    "rifugio",
    "rigenerazione",
    "rigidezza",
    "rinascita",
    "rinnovamento",
    "riposo",
    "riproduzione",
    "risate",
    "riserva",
    "riso",
    "risposte",
    "risultati",
    "ritorni",
    "ritratti",
    "riunioni",
    "rivelazione",
    "robustezza",
    "rotazioni",
    "rugiade",
    "rum",
    "sacchi a pelo",
    "saggezze",
    "sake",
    "salse",
    "salvaguardia",
    "santuari",
    "santuario",
    "saponette",
    "scambi",
    "scatole",
    "scenario",
    "scene",
    "scetticismo",
    "scherzi",
    "schiavitù",
    "sciarpe",
    "scintille",
    "scivoli per bambini",
    "sconcerto",
    "scoperta",
    "scorcio",
    "scotch",
    "sculture",
    "secchielli e palettine per la spiaggia",
    "sedie",
    "sedie da campeggio",
    "segnalazione",
    "segno",
    "seminari",
    "sensazione",
    "sensibilità",
    "sensualità",
    "sentieri",
    "sentimento",
    "servitù",
    "sfiducia",
    "sgabelli",
    "simposi",
    "sinagoghe",
    "singolarità",
    "situazioni senza uscita",
    "skateboard",
    "sofferenza",
    "soffi",
    "solidità",
    "sorpresa",
    "sorrisi",
    "sorveglianza",
    "sospetto",
    "sostanza",
    "sostegni",
    "sottomarini",
    "sottomissione",
    "sovrapposizione",
    "spazzole",
    "spazzolini",
    "speaker portatili",
    "spettacoli",
    "spettacoli circensi",
    "spettacolo",
    "spezie",
    "spostamenti",
    "spumante",
    "squame",
    "stabilità",
    "stagni",
    "stati",
    "statue",
    "stimoli",
    "strade",
    "strati",
    "strumenti musicali giocattolo",
    "strutturazione",
    "stupore",
    "subordinazione",
    "successo",
    "succhi di frutta",
    "suggerimenti",
    "supporto",
    "svago",
    "sviluppi",
    "sviluppo",
    "svolgimento",
    "tappeti",
    "tastiere",
    "tavoli da campeggio",
    "tazze da caffè",
    "tazze da tè",
    "teglie",
    "televisori",
    "templi",
    "tempo libero",
    "temporali",
    "tenacia",
    "tendoni",
    "tenerezza",
    "tensione",
    "tentacoli",
    "tequila",
    "termos",
    "terrore",
    "tifoni",
    "tolleranza",
    "torcia",
    "torcie",
    "tornadi",
    "torri",
    "torte",
    "tovaglie",
    "transiti",
    "trapunte",
    "trasformazione",
    "trasformazioni",
    "trasmissioni",
    "tricicli",
    "trionfo",
    "tristezza",
    "trolley",
    "tsunami",
    "tubi da snorkeling",
    "tuoni",
    "tutela",
    "tè",
    "unicità",
    "unione",
    "uragani",
    "vacanza",
    "valanghe",
    "variazioni",
    "veduta",
    "vedute",
    "venti",
    "verdura",
    "vibrazioni",
    "vicoli ciechi",
    "vie",
    "vigilanza",
    "vigorosità",
    "vincoli",
    "vino",
    "visione",
    "vita",
    "vitalità",
    "vittoria",
    "vivacità",
    "vodka",
    "voli",
    "voluminosità",
    "vortici",
    "whisky",
    "workshop",
    "zaini",
    "zampe",
    "zanne",
    "zanzariere",
  ],
  two: [
    "con l'odore della pioggia",
    "con profumo di fiori selvatici",
    "con riflessi dorati",
    "con un battito di cuore",
    "con un richiamo alla natura",
    "con un segreto nascosto",
    "con un sentore di avventura epica",
    "con un sorriso contagioso",
    "con un sorriso d'argento",
    "con un sorso di avventura",
    "con un tocco di dramma",
    "con un tocco di eleganza",
    "con un tocco di follia",
    "con un tocco di magia",
    "con un'anima errante",
    "con un'anima poetica",
    "con un'anima ribelle",
    "con un'anima selvaggia",
    "con una carezza di serenità",
    "con una nota di malinconia",
    "con una nota di mistero",
    "con una nota di romanticismo",
    "con una pennellata di colore",
    "con una punta di sarcasmo",
    "con una scia di avventura",
    "con una spruzzata di magia",
    "con una traccia di nostalgia",
    "di cioccolato fondente",
    "di cristallo",
    "di foresta incantata",
    "di fuoco e ghiaccio",
    "di mezzogiorno",
    "di mistero e suspense",
    "di neve candida",
    "di notte",
    "di paradiso perduto",
    "di passione ardente",
    "di pioggia primaverile",
    "di pura fantasia",
    "di riflessione",
    "di risveglio",
    "di sabbia dorata",
    "di sogni infranti",
    "di sogno",
    "di stelle cadenti",
    "di tempesta imminente",
    "di tenebre e luce",
    "di tramonto",
    "di tramonto dorato",
    "di velluto",
    "di viaggio intergalattico",
    "dopo una lunga meditazione",
    "durante la luna piena",
    "durante un viaggio intergalattico",
    "durante un'aurora boreale",
    "durante una lezione di yoga",
    "durante una notte insonne",
    "in bilico sul destino",
    "in stile vintage",
    "in un laboratorio segreto",
    "in un momento di pura ispirazione",
    "in un mondo di meraviglie",
    "in un mondo digitale",
    "in un mondo in cui la fisica è diversa",
    "in un mondo in cui la magia è reale",
    "in un mondo incantato",
    "in un mondo parallelo",
    "in un mondo sconosciuto",
    "in un regno di incantesimi",
    "in un regno di luce celeste",
    "in un regno di luce eterna",
    "in un regno di magia",
    "in un regno di magia e meraviglie",
    "in un regno di magia eterna",
    "in un regno fatato",
    "in un regno incantato",
    "in un regno magico",
    "in un sogno lucido",
    "in un universo parallelo",
    "in un'atmosfera di mistero",
    "in un'atmosfera surreale",
    "in un'epoca dimenticata",
    "in una dimensione alternativa",
    "mentre si ascolta musica classica",
    "nel bel mezzo di un'esplosione di colori",
    "nella mente di un alchimista",
    "nella mente di un angelo",
    "nella mente di un artista",
    "nella mente di un bambino curioso",
    "nella mente di un druido",
    "nella mente di un essere celeste",
    "nella mente di un essere celestiale",
    "nella mente di un essere divino",
    "nella mente di un essere etereo",
    "nella mente di un essere eterno",
    "nella mente di un fauno",
    "nella mente di un filosofo",
    "nella mente di un folle",
    "nella mente di un guaritore",
    "nella mente di un inventore visionario",
    "nella mente di un mago",
    "nella mente di un mago supremo",
    "nella mente di un matematico pazzo",
    "nella mente di un pazzo",
    "nella mente di un poeta",
    "nella mente di un poeta romantico",
    "nella mente di un sognatore",
    "nella mente di un viaggiatore",
    "nella mente di un visionario",
    "nella mente di una divinità antica",
    "nella mente di una divinità celeste",
    "nella mente di una sibilla",
    "nella mente di una strega",
    "nella mente di uno scienziato pazzo",
    "nella mente di uno stregone",
    "nella scia di una cometa",
    "sotto il guardiano di una stella cadente",
    "sotto il respiro di un angelo",
    "sotto il respiro di un drago",
    "sotto il respiro di un elfo",
    "sotto il respiro di un unicorno",
    "sotto il respiro di una dea",
    "sotto il respiro di una divinità",
    "sotto il respiro di una divinità antica",
    "sotto il respiro di una ninfa",
    "sotto il respiro di una sirena",
    "sotto il riflesso di una pozza d'acqua",
    "sotto il tocco di una fata",
    "sotto la luce del sole al tramonto",
    "sotto la luce della luna piena",
    "sotto la protezione di un angelo",
    "sotto una pioggia di stelle cadenti",
    "sulla cresta di un'onda",
    "sulla cresta di una montagna",
    "tra le pagine di un libro di fantascienza",
  ],
  nerd: [
    "Codemotion",
    "Byte",
    "Pixel",
    "Algoritmo",
    "Codice",
    "Debugging",
    "Server",
    "Cloud",
    "Hardware",
    "Software",
    "Hacker",
    "Bit",
    "Firewall",
    "Database",
    "C++",
    "Python",
    "JavaScript",
    "AI (Intelligenza Artificiale)",
    "Router",
    "Linux",
    "Terminale",
    "Bug",
    "Compilatore",
    "Framework",
    "API",
    "GitHub",
    "Encryption",
    "Codice binario",
    "HTML",
    "CSS",
    "IoT (Internet of Things)",
    "Firmware",
    "VR (Realtà Virtuale)",
    "AR (Realtà Aumentata)",
    "Blockchain",
    "Cybersecurity",
    "Quantum Computing",
    "SSD",
    "HTTP",
    "FTP",
    "LAN",
    "GUI (Interfaccia Grafica)",
    "Open Source",
    "Kernel",
    "Emulatore",
    "BIOS",
    "Overclocking",
    "Proxy",
    "URL",
    "DNS",
    "Torrent",
  ],
};