export default {
  languageCode: "it",
  languageName: "Italiano",
  conjunction: "e",
  one: [
    "accappatoi",
    "accoglienza",
    "accumulo",
    "acqua minerale",
    "acrobazie",
    "action figure",
    "adesione",
    "aerei",
    "affetto",
    "affinità",
    "aiutanti",
    "ali",
    "aliti",
    "allegria",
    "altalene",
    "ammirazione",
    "amore",
    "angolazione",
    "angoscia",
    "ansia",
    "apparizione",
    "aquiloni",
    "architetture",
    "arcobaleni",
    "armonia",
    "arti",
    "asciugamani",
    "asilo",
    "assemblee",
    "assistenti",
    "attenzione",
    "attività",
    "attrazione",
    "autenticità",
    "avanzamento",
    "avvenimenti",
    "awareness",
    "azioni",
    "balletti",
    "ballo",
    "bambole",
    "banchi di nebbia",
    "barche",
    "barriere",
    "basiliche",
    "bassorilievi",
    "battute",
    "bavaglini",
    "bevande gassate",
    "biciclette",
    "birra",
    "biscotti",
    "bloody mary",
    "bolle",
    "borracce",
    "borse termiche",
    "brandy",
    "brezze",
    "bufere",
    "burbon",
    "bussola",
    "busti",
    "caffè",
    "caipirinha",
    "calore",
    "cambiamenti",
    "canoe",
    "caramelle",
    "carattere",
    "caricabatterie portatili",
    "carne",
    "carrelli",
    "castelli",
    "cattedrali",
    "cavi usb",
    "celebrazione",
    "champagne",
    "chiese",
    "chiome",
    "ciclone",
    "cinture",
    "cioccolata",
    "ciotole",
    "cocktail",
    "coerenza",
    "coincidenza",
    "collaboratori",
    "collaborazione",
    "collari",
    "colloqui",
    "coltelli",
    "comprendere",
    "comprensione",
    "comunicazione",
    "comunione",
    "concerti",
    "concetti",
    "conclusione",
    "concordia",
    "condimenti",
    "condivisione",
    "condizioni",
    "conferenze",
    "confusione",
    "conoscenza",
    "conseguenze",
    "conservazione",
    "consistenza",
    "contenitori ermetici",
    "continuità",
    "contraddizione",
    "controlli",
    "convegni",
    "convergenza",
    "conversazioni",
    "cooperazione",
    "coperte",
    "copripiumini",
    "corde per saltare",
    "corna",
    "correnti",
    "corsie",
    "costanza",
    "costruzione",
    "costruzioni",
    "creazione",
    "creme",
    "crescita",
    "creste",
    "cucchiai",
    "cuffie",
    "curiosità",
    "cuscini",
    "custodia",
    "danza",
    "delicatezza",
    "delusione",
    "dialoghi",
    "dibattiti",
    "dichiarazione",
    "dilettanti",
    "dipendenza",
    "dipinti",
    "direzioni",
    "disciplina",
    "discussioni",
    "disegni",
    "disperazione",
    "divertimento",
    "dolcezza",
    "dolore",
    "dubbi",
    "durata",
    "durezza",
    "edifici",
    "effetti",
    "elefanti",
    "elicotteri",
    "emergenza",
    "emozione",
    "empatia",
    "energia",
    "erbe aromatiche",
    "esibizioni",
    "esistenza",
    "esito",
    "espansione",
    "esplorazione",
    "esposizioni",
    "espressione",
    "espressioni",
    "essenza",
    "estasi",
    "euforia",
    "eventi",
    "evoluzione",
    "fatti",
    "felicità",
    "fenomeni",
    "fermezza",
    "festa",
    "fiori",
    "forchette",
    "formaggi",
    "formazione",
    "fornelli da campeggio",
    "fortezza",
    "forza",
    "fotografie",
    "frane",
    "freschezza",
    "frisbee",
    "frutta",
    "fuga",
    "fulmini",
    "gallerie",
    "gelati",
    "generazione",
    "gentilezza",
    "gesti",
    "gin",
    "giocattoli",
    "giocattoli educativi",
    "giochi",
    "gioia",
    "gioventù",
    "giraffe",
    "gloria",
    "gocce",
    "goccioline",
    "gommoni",
    "graffiti",
    "grandine",
    "griglie",
    "guardia",
    "gufi",
    "guida",
    "hobby",
    "idee",
    "identità",
    "illuminazioni",
    "illustrazioni",
    "immagini",
    "impedimenti",
    "incanto",
    "incarnazione",
    "incentivi",
    "incertezza",
    "incitamenti",
    "incontri",
    "indagine",
    "indecisione",
    "indicazioni",
    "inferiorità",
    "ingrandimento",
    "ingrossamento",
    "inibizioni",
    "integrità",
    "interazioni",
    "interesse",
    "interessi",
    "intimità",
    "intrattenimento",
    "intuizioni",
    "invenzione",
    "irradiazioni",
    "ispirazioni",
    "kayak",
    "laghi",
    "lagune",
    "lampade",
    "lampi",
    "lanterne",
    "lenzuola",
    "leoni",
    "limiti",
    "lucchetti",
    "luci",
    "macchinine",
    "manifestazione",
    "mantenimento",
    "mari",
    "maschere",
    "materassi",
    "materassini",
    "matite",
    "meraviglia",
    "miglioramento",
    "migrazioni",
    "modelli",
    "moltiplicazione",
    "monopattini",
    "monumenti",
    "mostre",
    "motivazioni",
    "mouse",
    "movimenti",
    "movimenti rotatori",
    "musei",
    "mutazioni",
    "nascita",
    "natura",
    "nervosismo",
    "neve",
    "nevicate",
    "nubi",
    "nudi",
    "numeri",
    "oceani",
    "ombrelli",
    "ombrelloni",
    "onde",
    "opere",
    "opposizione",
    "organizzazione",
    "originalità",
    "orizzonte",
    "oscillazioni",
    "osservazione",
    "ostacoli",
    "padelle",
    "paesaggi",
    "palazzi",
    "palloni",
    "paludi",
    "pane",
    "panorama",
    "pantaloni",
    "pantofole",
    "parrucche",
    "passaggi",
    "passatempi",
    "passione",
    "pasta",
    "pattini",
    "paura",
    "peli",
    "pellicce",
    "peluche",
    "pennarelli",
    "pentole",
    "percezione",
    "performance",
    "personalità",
    "pesci",
    "piacere",
    "piante",
    "piatti",
    "pinne",
    "piogge",
    "pistole ad acqua",
    "pitture",
    "piume",
    "piumini",
    "posate",
    "preoccupazione",
    "presenza",
    "processi",
    "progresso",
    "protezione",
    "punto di vista",
    "puzzle",
    "quadro",
    "raduni",
    "rane",
    "rappresentazioni",
    "realizzazione",
    "reazioni",
    "recite",
    "regolamentazione",
    "relax",
    "repellenti per insetti",
    "resistenza",
    "respiro",
    "restrizioni",
    "ricerca",
    "riconoscimento",
    "ricreazione",
    "riflessi",
    "rifugio",
    "rinascita",
    "riposo",
    "riproduzione",
    "risate",
    "riserva",
    "riso",
    "risposte",
    "risultati",
    "ritratti",
    "riunioni",
    "sacchi a pelo",
    "saggezza",
    "salse",
    "salvaguardia",
    "santuari",
    "saponette",
    "scambi",
    "scatole",
    "scene",
    "scetticismo",
    "scherzi",
    "schiavitù",
    "sciarpe",
    "scintille",
    "scivoli",
    "scoperta",
    "scotch",
    "sculture",
    "secchielli",
    "sedie",
    "segno",
    "seminari",
    "sensazione",
    "sensibilità",
    "sentieri",
    "sentimento",
    "sgabelli",
    "skateboard",
    "sofferenza",
    "solidità",
    "sorpresa",
    "sorrisi",
    "sorveglianza",
    "sospetto",
    "sostanza",
    "sostegni",
    "sottomarini",
    "sovrapposizione",
    "spazzolini",
    "speaker portatili",
    "spettacoli",
    "spumante",
    "squame",
    "stagni",
    "statue",
    "stimoli",
    "strade",
    "strati",
    "strumenti musicali",
    "stupore",
    "successo",
    "succhi di frutta",
    "suggerimenti",
    "supporto",
    "svago",
    "sviluppo",
    "tappeti",
    "tastiere",
    "tavoli",
    "tazze",
    "teglie",
    "televisori",
    "tempo libero",
    "temporali",
    "tendoni",
    "tentacoli",
    "termos",
    "terrore",
    "tifoni",
    "torcia",
    "tornadi",
    "torri",
    "torte",
    "tovaglie",
    "trapunte",
    "trasformazione",
    "tricicli",
    "trionfo",
    "tristezza",
    "tsunami",
    "tuoni",
    "tè",
    "unione",
    "vacanza",
    "valanghe",
    "variazioni",
    "venti",
    "verdura",
    "vibrazioni",
    "vie",
    "vigilanza",
    "vincoli",
    "vino",
    "vita",
    "vittoria",
    "voli",
    "workshop",
    "zaini",
    "zampe",
    "zanne",
    "zanzariere",
  ],
  two: [
    "con un richiamo alla natura",
    "con un segreto nascosto",
    "con un sentore di avventura epica",
    "con un sorriso contagioso",
    "con un sorso di avventura",
    "con un tocco di dramma",
    "con un tocco di eleganza",
    "con un tocco di follia",
    "con un tocco di magia",
    "con un'anima avventurosa",
    "con un'anima poetica",
    "con un'anima ribelle",
    "con un'anima selvaggia",
    "con una carezza di serenità",
    "con una nota di malinconia",
    "con una nota di mistero",
    "con una nota di romanticismo",
    "con una punta di sarcasmo",
    "con una spruzzata di magia",
    "con una traccia di nostalgia",
    "di cioccolato fondente",
    "di cristallo",
    "di fuoco e ghiaccio",
    "con un tocco di mistero e suspense",
    "di notte",
    "di pura fantasia",
    "al buio",
    "di sogni infranti",
    "in un sogno",
    "dopo una lunga meditazione",
    "durante la luna piena",
    "durante un viaggio intergalattico",
    "durante una lezione di yoga",
    "durante una notte insonne",
    "in stile vintage",
    "in un laboratorio segreto",
    "in un libro di Pirandello",
    "a Napoli",
    "in un mondo digitale",
    "in un mondo in cui la gravità è diversa",
    "in un mondo in cui la magia è reale",
    "in un mondo incantato",
    "in un mondo parallelo",
    "in un mondo sconosciuto",
    "in un regno fatato",
    "in un universo parallelo",
    "in un'atmosfera surreale",
    "in una dimensione alternativa",
    "mentre si ascolta musica classica",
    "nella mente di un informatico",
    "nella mente di un artista",
    "nella mente di un bambino",
    "nella mente di un manager",
    "nella mente di un essere eterno",
    "nella mente di un filosofo",
    "nella mente di un folle",
    "nella mente di un guaritore",
    "nella mente di un mago",
    "nella mente di un matematico pazzo",
    "nella mente di un poeta",
    "nella mente di un poeta romantico",
    "nella mente di un sognatore",
    "nella mente di un viaggiatore",
    "nella mente di un visionario",
    "nella mente di una divinità antica",
    "nella mente di una strega",
    "nella mente di uno scienziato pazzo",
    "nella mente di uno stregone",
    "sotto il respiro di un unicorno",
    "sotto il riflesso di una pozza d'acqua",
    "sotto il tocco di una fata",
    "sotto la luce del sole al tramonto",
    "sotto la luce della luna piena",
    "sotto una pioggia di stelle cadenti",
    "tra le pagine di un libro di fantascienza",
    "ad hogwarts",
    "in biblioteca",
    "al cinema",
    "se venisse pubblicizzato da Apple",
    "in bianco e nero",
    "nel 3024",
  ],
  nerd: [
    "Codemotion",
    "Byte",
    "Pixel",
    "Algoritmo",
    "Codice",
    "Debugging",
    "Server",
    "Cloud",
    "Hardware",
    "Software",
    "Hacker",
    "Bit",
    "Firewall",
    "Database",
    "C++",
    "Python",
    "JavaScript",
    "AI",
    "Router",
    "Linux",
    "Terminale",
    "Bug",
    "Compilatore",
    "Framework",
    "API",
    "GitHub",
    "Encryption",
    "Codice binario",
    "HTML",
    "CSS",
    "IoT (Internet of Things)",
    "Firmware",
    "VR (Realtà Virtuale)",
    "AR (Realtà Aumentata)",
    "Blockchain",
    "Cybersecurity",
    "Quantum Computing",
    "SSD",
    "HTTP",
    "FTP",
    "LAN",
    "GUI (Interfaccia Grafica)",
    "Open Source",
    "Kernel",
    "Emulatore",
    "BIOS",
    "Overclocking",
    "Proxy",
    "URL",
    "DNS",
    "Torrent",
    "Browser",
    "VPN",
  ],
};
