export const one = [
  "Saponette",
  "Zaini",
  "Peluche",
  "Spazzolini",
  "Materassi",
  "Piumini",
  "Matite",
  "Sedie",
  "Cinture",
  "Ombrelli",
  "Sciarpe",
  "Collari",
  "Creme",
  "Biscotti",
  "Sgabelli",
  "Maschere",
  "Lucchetti",
  "Trolley",
  "Catamarani",
  "Lampade",
  "Spazzole",
  "Fulmini",
  "Pantaloni",
  "Parrucche",
  "Cuscini",
  "Televisori",
  "Tastiere",
  "Mouse",
  "Scatole",
  "Pennarelli",
  "Giraffe",
  "Elefanti",
  "Leoni",
  "Rane",
  "Gufi",
  "Elicotteri",
  "Aerei",
  "Sottomarini",
  "Barche",
  "Carrelli",
  "Piante",
  "Fiori",
  "Piatti",
  "Forchette",
  "Coltelli",
  "Cucchiai",
  "Tazze da tè",
  "Tazze da caffè",
  "Pentole",
  "Padelle",
  "Teglie",
  "Ciotole",
  "Spezie",
  "Erbe aromatiche",
  "Frutta",
  "Verdura",
  "Carne",
  "Pesce",
  "Formaggi",
  "Pane",
  "Pasta",
  "Riso",
  "Salse",
  "Condimenti",
  "Torte",
  "Gelati",
  "Cioccolata",
  "Caramelle",
  "Succhi di frutta",
  "Bevande gassate",
  "Acqua minerale",
  "Caffè",
  "Tè",
  "Vino",
  "Birra",
  "Cocktail",
  "Whisky",
  "Vodka",
  "Rum",
  "Gin",
  "Brandy",
  "Cognac",
  "Tequila",
  "Sake",
  "Scotch",
  "Burbon",
  "Champagne",
  "Prosecco",
  "Spumante",
  "Martini",
  "Negroni",
  "Mojito",
  "Daiquiri",
  "Margarita",
  "Pina Colada",
  "Cosmopolitan",
  "Caipirinha",
  "Bloody Mary",
  "Gin Tonic",
  "Irish Coffee",
  "Moscow Mule",
  "Coperte",
  "Copripiumini",
  "Lenzuola",
  "Asciugamani",
  "Tovaglie",
  "Tappeti",
  "Cuscini decorativi",
  "Trapunte",
  "Pantofole",
  "Accappatoi",
  "Bavaglini",
  "Cuscini per animali domestici",
  "Giocattoli",
  "Giocattoli educativi",
  "Action figure",
  "Bambole",
  "Macchinine",
  "Puzzle",
  "Costruzioni",
  "Strumenti musicali giocattolo",
  "Casette per bambini",
  "Scivoli per bambini",
  "Altalene per bambini",
  "Tricicli",
  "Biciclette per bambini",
  "Pattini a rotelle",
  "Monopattini",
  "Skateboard",
  "Palloni",
  "Frisbee",
  "Corde per saltare",
  "Aquiloni",
  "Pistole ad acqua",
  "Palloni da spiaggia",
  "Secchielli e palettine per la spiaggia",
  "Maschere da sub",
  "Pinne",
  "Tubi da snorkeling",
  "Gommoni",
  "Paddle board",
  "Kayak",
  "Canoe",
  "Tendoni",
  "Sacchi a pelo",
  "Materassini",
  "Cuscini gonfiabili",
  "Lanterne",
  "Torcie",
  "Zanzariere",
  "Repellenti per insetti",
  "Ombrelloni",
  "Sedie da campeggio",
  "Tavoli da campeggio",
  "Griglie da campeggio",
  "Posate da campeggio",
  "Batterie da campeggio",
  "Luci da campeggio",
  "Fornelli da campeggio",
  "Borse termiche",
  "Contenitori ermetici",
  "Borracce",
  "Termos",
  "Cuffie",
  "Speaker portatili",
  "Cavi USB",
  "Caricabatterie portatili",
  "Torcia",
  "Bussola",
  "Tentacoli",
  "Ali",
  "Zampe",
  "Corna",
  "Creste",
  "Zanne",
  "Squame",
  "Piume",
  "Pellicce",
  "Peli",
  "Ciuffi",
  "Ciuffetti",
  "Chiome",
  "Coadiuvanti",
  "Assistenti",
  "Aiutanti",
  "Collaboratori",
  "Sostegni",
  "Appoggi",
  "Stimoli",
  "Incitamenti",
  "Incentivi",
  "Motivazioni",
  "Folgori",
  "Scintille",
  "Fiammate",
  "Soffi",
  "Aliti",
  "Respiro",
  "Pulsazioni",
  "Battiti",
  "Vibrazioni",
  "Oscillazioni",
  "Irradiazioni",
  "Emanazioni",
  "Illuminazioni",
  "Ispirazioni",
  "Idee",
  "Concetti",
  "Cognizioni",
  "Comprensioni",
  "Discernimenti",
  "Saggezze",
  "Intuizioni",
  "Percezioni",
  "Suggerimenti",
  "Indicazioni",
  "Direzioni",
  "Orientamenti",
  "Guida",
  "Punto di riferimento",
  "Supporto",
  "Rifugio",
  "Asilo",
  "Santuario",
  "Benevolo",
  "Amorevole",
  "Cordialità",
  "Gentilezza",
  "Affabilità",
  "Accoglienza",
  "Calore",
  "Tolleranza",
  "Comprensione",
  "Empatia",
  "Sensibilità",
  "Dolcezza",
  "Carineria",
  "Tenerezza",
  "Delicatezza",
  "Sensualità",
  "Intimità",
  "Prossimità",
  "Affinità",
  "Attinenza",
  "Coincidenza",
  "Concordia",
  "Convergenza",
  "Armonia",
  "Unione",
  "Comunione",
  "Cooperazione",
  "Collaborazione",
  "Condivisione",
  "Mutualità",
  "Reciprocità",
  "Coerenza",
  "Continuità",
  "Persistenza",
  "Costanza",
  "Permanenza",
  "Durata",
  "Stabilità",
  "Fermezza",
  "Solidità",
  "Robustezza",
  "Resilienza",
  "Tenacia",
  "Durezza",
  "Rigidezza",
  "Fortezza",
  "Forza",
  "Vigorosità",
  "Energia",
  "Vitalità",
  "Vivacità",
  "Gioventù",
  "Freschezza",
  "Rigenerazione",
  "Rinascita",
  "Rinnovamento",
  "Trasformazione",
  "Evoluzione",
  "Miglioramento",
  "Progresso",
  "Avanzamento",
  "Crescita",
  "Sviluppo",
  "Espansione",
  "Ingrandimento",
  "Allargamento",
  "Dilatazione",
  "Inflazione",
  "Ingrossamento",
  "Voluminosità",
  "Moltiplicazione",
  "Riproduzione",
  "Procreazione",
  "Generazione",
  "Creazione",
  "Nascita",
  "Formazione",
  "Costruzione",
  "Organizzazione",
  "Strutturazione",
  "Disciplina",
  "Regolamentazione",
  "Normazione",
  "Conformità",
  "Adesione",
  "Obbedienza",
  "Sottomissione",
  "Assoggettamento",
  "Dipendenza",
  "Servitù",
  "Schiavitù",
  "Subordinazione",
  "Inferiorità",
  "Sovrapposizione",
  "Accumulo",
  "Riserva",
  "Conservazione",
  "Preservazione",
  "Mantenimento",
  "Salvaguardia",
  "Protezione",
  "Tutela",
  "Guardia",
  "Custodia",
  "Vigilanza",
  "Attenzione",
  "Osservazione",
  "Sorveglianza",
  "Controlli",
  "Limiti",
  "Restrizioni",
  "Vincoli",
  "Impedimenti",
  "Ostacoli",
  "Barriere",
  "Inibizioni",
  "Repressioni",
  "Riflessi",
  "Reazioni",
  "Risposte",
  "Retroazioni",
  "Ritorni",
  "Restituzioni",
  "Conseguenze",
  "Effetti",
  "Risultati",
  "Outcome",
  "Conclusione",
  "Svolgimento",
  "Esito",
  "Successo",
  "Trionfo",
  "Vittoria",
  "Gloria",
  "Celebrazione",
  "Festa",
  "Allegria",
  "Divertimento",
  "Gioia",
  "Felicità",
  "Euforia",
  "Estasi",
  "Folgorazione",
  "Fascinazione",
  "Ammirazione",
  "Meraviglia",
  "Sorpresa",
  "Stupore",
  "Incanto",
  "Ammaliamento",
  "Affascinamento",
  "Attrazione",
  "Risate",
  "Sorrisi",
  "Battute",
  "Scherzi",
  "Giochi",
  "Attività",
  "Passatempi",
  "Dilettanti",
  "Hobby",
  "Interessi",
  "Piacere",
  "Svago",
  "Relax",
  "Riposo",
  "Tempo libero",
  "Vacanza",
  "Fuga",
  "Relax",
  "Ricreazione",
  "Intrattenimento",
  "Spettacolo",
  "Eventi",
  "Raduni",
  "Incontri",
  "Riunioni",
  "Assemblee",
  "Convegni",
  "Conferenze",
  "Seminari",
  "Workshop",
  "Simposi",
  "Colloqui",
  "Dibattiti",
  "Discussioni",
  "Dialoghi",
  "Conversazioni",
  "Scambi",
  "Interscambi",
  "Interazioni",
  "Comunicazioni",
  "Trasmissioni",
  "Espressioni",
  "Arti",
  "Sculture",
  "Pitture",
  "Dipinti",
  "Disegni",
  "Illustrazioni",
  "Graffiti",
  "Fotografie",
  "Immagini",
  "Ritratti",
  "Panorami",
  "Vedute",
  "Paesaggi",
  "Naturalezze morte",
  "Nudi",
  "Rappresentazioni",
  "Modelli",
  "Statue",
  "Busti",
  "Bassorilievi",
  "Altorilievi",
  "Monumenti",
  "Memoriali",
  "Architetture",
  "Edifici",
  "Palazzi",
  "Castelli",
  "Fortezze",
  "Torri",
  "Chiese",
  "Cattedrali",
  "Basiliche",
  "Santuari",
  "Templi",
  "Moschee",
  "Sinagoghe",
  "Musei",
  "Gallerie",
  "Mostre",
  "Esposizioni",
  "Rassegne",
  "Spettacoli",
  "Concerti",
  "Esibizioni",
  "Performance",
  "Recital",
  "Opere",
  "Balletti",
  "Danza",
  "Ballo",
  "Spettacoli circensi",
  "Acrobazie",
  "Numeri",
  "Recite",
  "Scene",
  "Atti",
  "Azioni",
  "Gesti",
  "Comportamenti",
  "Movimenti",
  "Passaggi",
  "Avvenimenti",
  "Fatti",
  "Fenomeni",
  "Processi",
  "Procedimenti",
  "Progressi",
  "Sviluppi",
  "Cambiamenti",
  "Trasformazioni",
  "Evoluzioni",
  "Mutazioni",
  "Variazioni",
  "Fluttuazioni",
  "Flussi",
  "Spostamenti",
  "Migrazioni",
  "Voli",
  "Transiti",
  "Corsie",
  "Vie",
  "Strade",
  "Sentieri",
  "Mari",
  "Oceani",
  "Laghi",
  "Stagni",
  "Lagune",
  "Paludi",
  "Maree",
  "Onde",
  "Correnti",
  "Venti",
  "Brezze",
  "Gelate",
  "Nevicate",
  "Bufere",
  "Temporali",
  "Tuoni",
  "Lampi",
  "Arcobaleni",
  "Nebbie",
  "Nubi",
  "Cumuli",
  "Strati",
  "Banchi di nebbia",
  "Bolle",
  "Goccioline",
  "Gocce",
  "Rugiade",
  "Piogge",
  "Grandine",
  "Neve",
  "Brine",
  "Valanghe",
  "Frane",
  "Tsunami",
  "Tornadi",
  "Ciclone",
  "Uragani",
  "Tifoni",
  "Vortici",
  "Rotazioni",
  "Movimenti rotatori",
  "Vicoli ciechi",
  "Impasse",
  "Situazioni senza uscita",
  "Stati",
  "Condizioni",
  "Circostanze",
  "Casi",
  "Scenario",
  "Quadro",
  "Panorama",
  "Orizzonte",
  "Paesaggio",
  "Scorcio",
  "Veduta",
  "Visione",
  "Prospettiva",
  "Punto di vista",
  "Angolazione",
  "Esplorazione",
  "Ricerca",
  "Indagine",
  "Scoperta",
  "Invenzione",
  "Rivelazione",
  "Manifestazione",
  "Emergenza",
  "Apparizione",
  "Materializzazione",
  "Realizzazione",
  "Concretizzazione",
  "Attualizzazione",
  "Incarnazione",
  "Corporificazione",
  "Sostanza",
  "Essenza",
  "Natura",
  "Carattere",
  "Personalità",
  "Identità",
  "Singolarità",
  "Unicità",
  "Originalità",
  "Autenticità",
  "Genuinità",
  "Integrità",
  "Consistenza",
  "Presenza",
  "Esistenza",
  "Vita",
  "Espressione",
  "Dichiarazione",
  "Comunicazione",
  "Segnalazione",
  "Indicazione",
  "Segno",
  "Riconoscimento",
  "Conoscenza",
  "Consciousness",
  "Awareness",
  "Percezione",
  "Comprendere",
  "Sensazione",
  "Sentimento",
  "Emozione",
  "Passione",
  "Affetto",
  "Amore",
  "Tristezza",
  "Dolore",
  "Sofferenza",
  "Angoscia",
  "Disperazione",
  "Paura",
  "Terrore",
  "Tensione",
  "Ansia",
  "Nervosismo",
  "Preoccupazione",
  "Interesse",
  "Curiosità",
  "Delusione",
  "Disillusione",
  "Sconcerto",
  "Confusione",
  "Perplessità",
  "Incertezza",
  "Dubbi",
  "Indecisione",
  "Ambivalenza",
  "Contraddizione",
  "Opposizione",
  "Resistenza",
  "Sfiducia",
  "Sospetto",
  "Scetticismo",
  // "Attrattiva",
  // "Seducente",
  // "Attraente",
  // "Suggestiva",
  // "Irradiante",
  // "Luminosa",
  // "Raggiante",
  // "Scintillante",
  // "Splendente",
  // "Brillante",
  // "Fulgidamente",
  // "Luccicante",
  // "Bagliore",
  // "Favoloso",
  // "Straordinario",
  // "Eccezionale",
  // "Incredibile",
  // "Fantastico",
  // "Meraviglioso",
  // "Stupendo",
  // "Magnifico",
  // "Grandioso",
  // "Maestoso",
  // "Elegante",
  // "Raffinato",
  // "Stiloso",
  // "Chic",
  // "Fashionable",
  // "Moderno",
  // "All'avanguardia",
  // "Progressivo",
  // "Innovativo",
  // "Creativo",
  // "Fantasia",
  // "Immaginario",
  // "Visionario",
  // "Sognatore",
  // "Romantico",
  // "Poetico",
  // "Passionale",
  // "Sentimentale",
  // "Emotivo",
  // "Empatico",
  // "Affettuoso",
  // "Tenero",
  // "Dolce",
  // "Amabile",
  // "Delizioso",
  // "Incantevole",
  // "Gentile",
  // "Caro",
];

export const two = [
  "con riflessi dorati",
  "di cristallo",
  "con un tocco di magia",
  "di velluto",
  "con l'odore della pioggia",
  "in stile vintage",
  "con una nota di mistero",
  "avvolti in nebbia",
  "di luna piena",
  "con una carezza di vento",
  "di fuoco e ghiaccio",
  "incantati",
  "con profumo di fiori selvatici",
  "di cioccolato fondente",
  "con un sorriso contagioso",
  "avvolti in seta",
  "in bilico sul destino",
  "di stelle cadenti",
  "inseparabili",
  "con un segreto nascosto",
  "di notte",
  "in una dimensione alternativa",
  "avvolti nel silenzio",
  "con un'anima ribelle",
  "di sabbia dorata",
  "con una scia di avventura",
  "di mezzogiorno",
  "in un mondo parallelo",
  "avvolti nell'incanto",
  "con una nota di malinconia",
  "di tramonto",
  "con un tocco di eleganza",
  "di aurora boreale",
  "avvolti nell'oscurità",
  "con un richiamo alla natura",
  "di pura fantasia",
  "con una punta di sarcasmo",
  "di riflessione",
  "avvolti nell'atmosfera",
  "con un tocco di follia",
  "di pioggia primaverile",
  "con un battito di cuore",
  "di risveglio",
  "avvolti nell'illusione",
  "con un'anima poetica",
  "di tenebre e luce",
  "con una pennellata di colore",
  "di alba",
  "con un sorso di avventura",
  "di sogno",
  "avvolti nell'intrigo",
  "con una spruzzata di magia",
  "di mistero e suspense",
  "con una traccia di nostalgia",
  "di aurora australis",
  "con un tocco di dramma",
  "di paradiso perduto",
  "avvolti nella leggenda",
  "con una nota di romanticismo",
  "di avventura epica",
  "con un sorriso d'argento",
  "di neve candida",
  "avvolti nella meraviglia",
  "con un'anima selvaggia",
  "di tempesta imminente",
  "con una carezza di serenità",
  "di sogni infranti",
  "avvolti nel mistero",
  "di passione ardente",
  "con un'anima errante",
  "di foresta incantata",
  "di tramonto dorato",
  "di viaggio intergalattico",
];

export const three = [
  "in un universo parallelo",
  "in un sogno lucido",
  "durante una lezione di yoga",
  "nel bel mezzo di un'esplosione di colori",
  "mentre si ascolta musica classica",
  "sotto una pioggia di stelle cadenti",
  "in un'atmosfera surreale",
  "come se fossero stati creati da un bambino",
  "come se fossero stati scolpiti da un maestro",
  "dopo una lunga meditazione",
  "nella mente di un matematico pazzo",
  "tra le pagine di un libro di fantascienza",
  "nella scia di una cometa",
  "in un laboratorio segreto",
  "come se fossero stati dipinti da un artista rinascimentale",
  "come se fossero stati scritti da un poeta romantico",
  "sulla cresta di un'onda",
  "come se fossero stati plasmati da un dio capriccioso",
  "durante una notte insonne",
  "sotto la luce della luna piena",
  "come se fossero stati intagliati da un artigiano abile",
  "come se fossero stati tessuti da una strega",
  "nella mente di un filosofo",
  "come se fossero stati modellati dall'argilla",
  "come se fossero stati forgiati dal fuoco",
  "in un mondo digitale",
  "come se fossero stati intessuti da magia",
  "nella mente di un bambino curioso",
  "come se fossero stati sussurrati dalla natura",
  "sotto la luce del sole al tramonto",
  "come se fossero stati ispirati da un sogno",
  "come se fossero stati incisi nella pietra",
  "in un momento di pura ispirazione",
  "come se fossero stati plasmati dal vento",
  "nella mente di un poeta",
  "come se fossero stati intagliati da ghiaccio",
  "come se fossero stati ricamati da fate",
  "durante un viaggio intergalattico",
  "sulla cresta di una montagna",
  "in un mondo in cui la fisica è diversa",
  "come se fossero stati dipinti da un pittore impressionista",
  "come se fossero stati intessuti da un'arpa celestiale",
  "nella mente di un inventore visionario",
  "come se fossero stati plasmati dalla mente di un artista",
  "come se fossero stati trasportati da un'onda radio",
  "durante un'aurora boreale",
  "in un'epoca dimenticata",
  "come se fossero stati intrecciati da fate",
  "sotto il riflesso di una pozza d'acqua",
  "come se fossero stati sospinti dal vento solare",
  "in un mondo in cui la magia è reale",
  "come se fossero stati dipinti da un pittore surreale",
  "nella mente di un sognatore",
  "come se fossero stati modellati dal destino",
  "come se fossero stati plasmati da una mente geniale",
  "sotto la protezione di un angelo",
  "come se fossero stati trasportati da un'onda sonora",
  "nella mente di un viaggiatore",
  "come se fossero stati scolpiti da un artista visionario",
  "come se fossero stati intrecciati da draghi",
  "in un'atmosfera di mistero",
  "come se fossero stati plasmati dalla luce stellare",
  "come se fossero stati scolpiti dall'oceano",
  "nella mente di uno scienziato pazzo",
  "come se fossero stati intessuti da fate",
  "come se fossero stati plasmati dalla mente di un folle",
  "in un mondo di meraviglie",
  "come se fossero stati dipinti da un artista folle",
  "come se fossero stati intrecciati da un incantesimo",
  "nella mente di un visionario",
  "come se fossero stati plasmati da un'energia ignota",
  "come se fossero stati trasportati da un sogno",
  "sotto il tocco di una fata",
  "come se fossero stati intessuti dalla trama del destino",
  "come se fossero stati plasmati dalla mente di un genio",
  "nella mente di un poeta romantico",
  "come se fossero stati trasportati da un raggio laser",
  "come se fossero stati scolpiti da un artista pazzo",
  "in un mondo sconosciuto",
  "come se fossero stati dipinti da un pittore celestiale",
  "come se fossero stati intrecciati da streghe",
  "nella mente di un folle",
  "come se fossero stati plasmati da un'entità cosmica",
  "come se fossero stati trasportati da un'onda elettromagnetica",
  "sotto il guardiano di una stella cadente",
  "come se fossero stati intessuti da un incantesimo",
  "come se fossero stati plasmati dalla mente di un mago",
  "nella mente di un artista",
  "come se fossero stati trasportati da un'energia spirituale",
  "in un regno magico",
  "come se fossero stati dipinti da un pittore visionario",
  "come se fossero stati scolpiti da un angelo",
  "nella mente di un pazzo",
  "come se fossero stati plasmati da un'entità divina",
  "come se fossero stati trasportati da un raggio cosmico",
  "sotto il respiro di un drago",
  "come se fossero stati intessuti da un incantesimo antico",
  "come se fossero stati plasmati dalla mente di un dio",
  "nella mente di un mago",
  "come se fossero stati trasportati da un'onda gravitazionale",
  "in un mondo incantato",
  "come se fossero stati scolpiti da un dio",
  "come se fossero stati intrecciati da una fata",
  "come se fossero stati plasmati da un'energia misteriosa",
  "come se fossero stati trasportati da un'onda luminosa",
  "sotto il respiro di una sirena",
  "come se fossero stati intessuti da un incantesimo magico",
  "come se fossero stati plasmati dalla mente di una divinità",
  "nella mente di uno stregone",
  "come se fossero stati trasportati da un'energia cosmica",
  "come se fossero stati dipinti da un artista pazzo",
  "in un regno fatato",
  "come se fossero stati scolpiti da una dea",
  "come se fossero stati intrecciati da un incantesimo potentissimo",
  "nella mente di un alchimista",
  "come se fossero stati plasmati da un'entità magica",
  "come se fossero stati trasportati da un raggio di luce",
  "sotto il respiro di un unicorno",
  "come se fossero stati intessuti da un incantesimo millenario",
  "come se fossero stati plasmati dalla mente di una fata",
  "nella mente di una strega",
  "come se fossero stati trasportati da un'energia mistica",
  "come se fossero stati dipinti da un artista geniale",
  "in un regno incantato",
  "come se fossero stati scolpiti da un mago",
  "come se fossero stati intrecciati da un incantesimo sacro",
  "nella mente di un druido",
  "come se fossero stati plasmati da un'entità celeste",
  "come se fossero stati trasportati da un raggio di speranza",
  "sotto il respiro di una ninfa",
  "come se fossero stati intessuti da un incantesimo divino",
  "come se fossero stati plasmati dalla mente di una dea",
  "nella mente di un angelo",
  "come se fossero stati trasportati da un'energia vitale",
  "come se fossero stati dipinti da un artista ispirato",
  "in un regno di magia",
  "come se fossero stati scolpiti da una strega",
  "come se fossero stati intrecciati da un incantesimo potente",
  "nella mente di un guaritore",
  "come se fossero stati plasmati da un'entità mistica",
  "come se fossero stati trasportati da un raggio di amore",
  "sotto il respiro di un elfo",
  "come se fossero stati plasmati dalla mente di un dio antico",
  "nella mente di un fauno",
  "come se fossero stati trasportati da un'energia sacra",
  "come se fossero stati dipinti da un artista divino",
  "in un regno di incantesimi",
  "come se fossero stati scolpiti da un druido",
  "come se fossero stati intrecciati da un incantesimo eterno",
  "nella mente di una sibilla",
  "come se fossero stati trasportati da un raggio di luce eterna",
  "sotto il respiro di una dea",
  "come se fossero stati intessuti da un incantesimo celeste",
  "come se fossero stati plasmati dalla mente di una divinità antica",
  "nella mente di un essere etereo",
  "come se fossero stati dipinti da un artista celeste",
  "in un regno di magia e meraviglie",
  "come se fossero stati scolpiti da una fata",
  "nella mente di un mago supremo",
  "sotto il respiro di un angelo",
  "come se fossero stati intessuti da un incantesimo eterno",
  "nella mente di un essere celestiale",
  "in un regno di luce eterna",
  "come se fossero stati scolpiti da una divinità antica",
  "come se fossero stati intrecciati da un incantesimo celeste",
  "nella mente di un essere divino",
  "come se fossero stati plasmati da un'entità eterea",
  "come se fossero stati trasportati da un raggio di luce celeste",
  "sotto il respiro di una divinità",
  "come se fossero stati plasmati dalla mente di un essere celeste",
  "nella mente di una divinità antica",
  "come se fossero stati trasportati da un'energia eterea",
  "come se fossero stati dipinti da un artista etereo",
  "in un regno di magia eterna",
  "come se fossero stati scolpiti da un'entità divina",
  "come se fossero stati intrecciati da un incantesimo etereo",
  "nella mente di un essere eterno",
  "sotto il respiro di una divinità antica",
  "come se fossero stati plasmati dalla mente di un essere divino",
  "nella mente di una divinità celeste",
  "come se fossero stati trasportati da un'energia eterna",
  "in un regno di luce celeste",
  "come se fossero stati scolpiti da una divinità eterea",
  "come se fossero stati intrecciati da un incantesimo divino",
  "nella mente di un essere celeste",
];

export function getRandomTitle(level = 1) {
  let title = one[Math.floor(Math.random() * one.length)];

  if (level === 2) {
    title += ` ${two[Math.floor(Math.random() * two.length)]}`;
  }
  if (level === 3) {
    title += ` ${three[Math.floor(Math.random() * three.length)]}`;
  }
  return title;
}
